### ISSUE TITLE
Warnings are reported as issues in the bottom toolbar

### ISSUE THREAD

**Issue by rvion** [nwolverson/atom-ide-purescript#100]
![image](https://cloud.githubusercontent.com/assets/2150990/16803091/a32c6e1e-4904-11e6-9854-daaf5b4872ff.png)

It is possible to change the wording ?

**Comment by nwolverson** [comment]
No, that's the purview of linter - and I think issues includes all severity, including errors, warnings, info, whatever there is. I think it's been raised with linter that the overall count is less than useful, suggest following up if you are interested. The only part of the bottom toolbar owned by this package is the tick/purescript part.

We raise issues as warning and error corresponding exactly to compiler warnings / errors. I think this is all as it should be.
