### ISSUE TITLE
[Speed issue] pscid is ~5 to 10 times faster to report errors and warnings than atom-ide-purescript

### ISSUE THREAD

**Issue by rvion** [nwolverson/atom-ide-purescript#102]
on a small project (~6/7 modules for now) [pscid](https://github.com/kRITZCREEK/pscid) is between 5 and 10 times faster to re-typecheck my code and report errors than the plugin. 

ping @kRITZCREEK @nwolverson: is there anything I can do to bring the same speed to atop-ide-purescript ?

**Comment by garyb** [comment]
Have you enabled fast rebuild support?

**Comment by rvion** [comment]
@garyb no, I didn't, and indeed, after activation, it suddenly became fast !

now, I'm wondering: 
- Shouldn't "fast rebuild" be the default ?

---

Thank you all for being so responsive ! Purescript is purely awesome ❤️ 
You have one more commercial user !

**Comment by rvion** [comment]
Shouldn't "fast rebuild" be the default ?

**Comment by nwolverson** [comment]
Possibly. I didn't want to break any existing setup with the reliance on psc-ide, particularly the way it was distributed at the time.

Going to make a "break things" release with multiple-server support so that may be a good point to change this too.
