### ISSUE TITLE
deleted modules stay in the autocompletion list

### ISSUE THREAD

**Issue by rvion** [nwolverson/atom-ide-purescript#105]
(with fast-build + `pulp --watch build --to test.js` running along atom)

🔶  after relocating my `Behaviour`module as GM.behaviour, I can still see the module appears in the autocompletion list

![image](https://cloud.githubusercontent.com/assets/2150990/16850305/bffb99de-49fe-11e6-8826-d073afe2c0b8.png)

🔶 🔶  Restarting atom doesn't fix the problem, I need to manually trash my ./output folder to fix the problem -> 🍏

**Comment by kritzcreek** [comment]
This one has been known even before psc-ide was a thing ;) https://github.com/purescript/purescript/issues/1921. Just like the compiler, psc-ide can't really know if the source file for a module got deleted, because the externs file remains in the `output/`.

**Comment by nwolverson** [comment]
Feel like solving this for a single-file based approach like psc-ide fast rebuild probably isn't feasible, but per the linked issue full builds can surely notice removed modules.

Closing as not a plugin issue.

**Comment by rvion** [comment]
@kRITZCREEK is that so crazy for psc-ide to "solve" it via any of
- listening to FS events related to file move / file deletion / file rename
- checking at startup time if local modules still exist (so no runtime penalty, and restart ide-server would catch those ghost files)
- checking periodically if files still exist (every x seconds) for continuous self-sanity check ?
