### ISSUE TITLE
goto declaration is great -> but it starts a psc-ide-server everytime

### ISSUE THREAD

**Issue by rvion** [nwolverson/atom-ide-purescript#109]
🔶  goto declaration is great, but it starts a psc-ide-server everytime :)

Would it make more sense to start an ide-server only when needed  ? (autocompletion, file save, other mouse hovering)

I don't know what the memory footprint is, so it may just be better to leave it as-is. Just raising the issue in case it's an unfortunate behaviour

**Comment by nwolverson** [comment]
That shouldn't happen!

A psc-ide-server should be started once for a given "project" when a file is opened (more or less).

Not looked into this yet but I wonder, are you going to library definitions inside `bower_components` ? I think it's detecting those nested library directories as their own projects.

Thanks for the spot!

**Comment by kritzcreek** [comment]
Ouch :D each of the deps inside bower_components has a bower.json

**Comment by rvion** [comment]
> Not looked into this yet but I wonder, are you going to library definitions inside bower_components ? I think it's detecting those nested library directories as their own projects.

Yes, indeed. I was only speaking about when I use goto decl on functions imported from other libraries. everytime I do so, I see green popups about ide being launched as atom opens the file in bower_components

> Ouch :D each of the deps inside bower_components has a bower.json

yes, indeed :)

**Comment by rvion** [comment]
🍏 🍏  this being said, the ability to quickly open any file in bower components via goto-decl is awesome, 

The ability to start an ide-server is also sometimes usefull !
👉  It may just not worth it to start it when we just want to take a quick look at a function definition

**Comment by nwolverson** [comment]
Fixed by https://github.com/kRITZCREEK/purescript-psc-ide/commit/f1cdd169c1bd85ee7953cc789a5726628d39e7ad - need to make a release including this.
