### ISSUE TITLE
Add keywords to auto-completion list

### ISSUE THREAD

**Issue by sardonicpresence** [nwolverson/atom-ide-purescript#113]
If, as I commonly do, I type "do" followed (with a slight delay) by enter intended as a newline, I currently get a "dodgerblue" auto-completion inserted along with "import CSS (dodgerblue)"; hardly what I was hoping for.

I suspect including keywords in the auto-completion list would resolve the issue nicely.

**Comment by rvion** [comment]
I have the same problem.
adding keywords and templates to the autocompletion list would let me avoid pressing esc before hitting enter in many cases

**Comment by nwolverson** [comment]
Someone suggested they might add this but never came back. I'm torn as to whether to add this to this package or language-purescript (which claims to have snippets but does not).

**Comment by rvion** [comment]
Ahah, I noticed the false claim too ^^
My 2 cents: il would be more logical to have those in language-purescript, but quick and temporary workarounds are not necessarikly bad.

How about ading them in your package and offering language-purecript maintainer to move them in his package and open a PR to remove them from yours if he wants to ?

**Comment by nwolverson** [comment]
language-purescript now has snippets. Is there anything further to do here?

**Comment by nwolverson** [comment]
Fixed via snippets in language-purescript. If you have any issues with snippets for built-in keywords/syntax or want to contribute enhancements please raise an issue there https://github.com/purescript-contrib/atom-language-purescript
