### ISSUE TITLE
Behaviour of Enter inconsistent given auto-completion

### ISSUE THREAD

**Issue by sardonicpresence** [nwolverson/atom-ide-purescript#114]
It is unfortunate that whether or not a newline is inserted when I hit enter is dependent on whether or not I've just typed an auto-completed tag and the speed with which I typed vs. the speed of the auto-completion list popping-up.

I feel it would be more intuitive if Enter inserted a newline rather than an auto-completion iff the auto-completion replacement would not change the text i.e. it is an exact match.

This way auto-completion would be less disruptive to typing without introducing larger delays in the auto-completion pop-up.

**Comment by rvion** [comment]
> I feel it would be more intuitive if Enter inserted a newline rather than an auto-completion iff the auto-completion replacement would not change the text i.e. it is an exact match.

trigger autocompletion on an existing identifyer and pressing enter allows you to automatically import the identifyer in scope, so I'm not quite sure I would like this unless something like https://github.com/nwolverson/atom-ide-purescript/issues/98 is done before.

Also, if https://github.com/nwolverson/atom-ide-purescript/issues/113 is solved, I think the issue you're reporting here will be less of a problem

Finally, I think it's better to keep things consistent, and this behaviour would not be standard

so I'm rather **-1** on this proposal

**Comment by nwolverson** [comment]
I don't think this is particular to this package. This is the behaviour of https://github.com/atom/autocomplete-plus/ - in particular there is some configuration you can make on the autocomplete+ settings (like using tab instead of return), and you can find issues discussing enter behaviour on that repo.
