### ISSUE TITLE
Command to show type rather than needing to hover?

### ISSUE THREAD

**Issue by andrelevi** [nwolverson/atom-ide-purescript#118]
There are some great commands here: https://github.com/nwolverson/atom-ide-purescript/blob/master/keymaps/core.cson.

Is there a "hidden" one, by chance, for showing the type? Trying to avoid the mouse 😁 .

**Comment by nwolverson** [comment]
No, such a thing does not exist, but would be easy to add.

Well - on second thoughts, getting the cursor position & token at that position is done many places already, and obviously getting the type info, but I'm not sure how this should be displayed. Maybe as a bottom bar type thing? I think this is common for keyboard-driven info

**Comment by andrelevi** [comment]
Fwiw, `ide-haskell` shows it below the selected line, kind of like how you currently do with the mouse pointer:

<img width="436" alt="ide-haskell-type" src="https://cloud.githubusercontent.com/assets/5660708/17089119/a7b4f56e-5255-11e6-8643-78280aef60d0.png">

So I would think your current styling would at least match `ide-haskell`, if you just used cursor position rather than mouse pointer position. `ide-haskell` also then uses a command bound to `escape` to dismiss the tooltip.

Thanks for the awesome plugin :sunglasses:

**Comment by nwolverson** [comment]
Hmm. `ide-haskell` also displays its own tooltips, while we're using an external package right now and don't have the ability to control it in that way. Maybe something to think about when reworking tooltips.
