### ISSUE TITLE
Handle suggestions for qualified modules

### ISSUE THREAD

**Issue by nwolverson** [nwolverson/atom-ide-purescript#12]

**Comment by nwolverson** [comment]
As per https://github.com/epost/psc-ide-emacs/issues/9

**Comment by nwolverson** [comment]
This is in but I wonder if we can do better for `M.` - currently we get suggestions for `.` literally

**Comment by kritzcreek** [comment]
The empty prefix filter keeps everything. So you might want to try using that for whole module completion. I'll also try to parsing the qualifiers myself so you can pass me the fully qualified identifier and I resolve it for you.

Edit: I just tried it out. Just qualify a module and browse it :) Super handy

**Comment by nwolverson** [comment]
Just published a version using exactly this, the empty prefix, there was just a tweak required to cause this request to be made/replaced. Though worth noting I see a bunch of entries like this:

```
{ identifier: "", module: "module", type: "module" }
```

As for parsing qualifiers, that sounds good.
-  Currently if you type a `Qualified.valueIdentifier` then I will request `valueIdentifier` with module filter of `Qualified` (or the full module name if that was a qualified import). This is fine
-  For a `Qualified.UpperCaseIdent` then the same logic works to complete types
-  But to complete that as a module, I would want to pass `Qualified.UpperCaseIdent`

Problem being the case with 1 or more `.` which looks like either a type or module name.

**Comment by kritzcreek** [comment]
ide-haskell or haskell-mode etc. do that by having multiple contexts for completion

So when you're typing in a line that started with "import " they'll only give you module completions.

**Comment by nwolverson** [comment]
Sure, I guess it depends if you ever use fully qualified module names in expressions/types. I think I'm over-thinking it, if it's imported unqualified then you wouldn't want to do that, if it's not imported (diff here) then there's no good basis for completing it.
