### ISSUE TITLE
Package not started on resuming session

### ISSUE THREAD

**Issue by nwolverson** [nwolverson/atom-ide-purescript#120]
Think this is resurgence of an Atom issue.

**Comment by nwolverson** [comment]
Filed https://github.com/atom/atom/issues/12333 as this seems to be a regression on activationHooks - `language-purescript:grammar-used`

**Comment by starper** [comment]
This is fixed in atom `1.9.8`. Ide is started when you open atom and `.psc-ide-port` is removed when you close it.
