### ISSUE TITLE
Autocompletion doesn't work for functions that start with underscore

### ISSUE THREAD

**Issue by starper** [nwolverson/atom-ide-purescript#124]
It is possible that it's because of my problems with [101](https://github.com/nwolverson/atom-ide-purescript/issues/101), but I've noticed that ide doesn't see functions like `_Foo` at all.

**Comment by nwolverson** [comment]
Probably we've not customised the triggers for autocomplete+ - does the same hold for highlighting?

**Comment by starper** [comment]
No, I don't see any problems with highlighting. `_Foo` looks like any other function.

**Comment by nwolverson** [comment]
Sorry, I meant tooltips :(

**Comment by starper** [comment]
Tooltips seem to be ok.
