### ISSUE TITLE
Wrong path to local npm bin directory

### ISSUE THREAD

**Issue by starper** [nwolverson/atom-ide-purescript#129]
With `Use npm bin directory` option on, ide is trying to find `psc-ide-server` in `C:\path\to\folder\node_modules.bin` folder (the last backslash is lost).

**Comment by starper** [comment]
Oops, sorry, I was wrong. The problem was that I forgot to remove path from `executable location` field. `C:\path\to\folder\node_modules.bin` was shown in error message and I thought at first that it was the cause of an error.

**Comment by starper** [comment]
I took this path from error message `Couldn't find psc-ide-server, check PATH...`, but now I'm not sure that it causes this error. I removed path from `executable location` field and created `node_modules.bin` folder and copied everything from `.bin` in it and server started to work, but then I removed `node_modules.bin` folder and it is still working after reloading.

**Comment by nwolverson** [comment]
That option wasn't meant to be "enabled" yet, I thought I removed it from the settings... I originally had it working, I thought, but certainly it doesn't work for me just now.

I'll take another look.

**Comment by starper** [comment]
Thanks. I like this option. Every time I was creating a new project I thought about asking for something like this, but always forgot to actually do it :)

I like to have everything locally and it's what I really like about `npm`, but the previous approach when you have to manually copy `psc-ide-server` file to your main directory and add path to it, it was a little too complicated for such a simple task.

**Comment by nwolverson** [comment]
So is this now working for you? 

When you say "I removed path from executable location field" - the npm bin will only be used if you don't specify an actual path for the executable - it really is just added to the `PATH`, a full path will render this irrelevant.

**Comment by starper** [comment]
Yes it is working now. It didn't at first, even with path to the executable removed, so I thought that this was because of the wrong path in error message (the one without backslash) and I created this issue. After this my actions were quite random, like creating and removing `node_modules.bin` folder, turning this option on/off several times, reloading editor and so on. One of my actions was to remove everything from `projects.cson` (I use `project manager` package and all my settings are specified in `projects.cson`), I'm not sure, but I think there was something wrong in it that caused this error.

So if you don't have any problems with this option, I guess you can close this issue.

**Comment by nwolverson** [comment]
By error message do you mean the popup message or the error logged in the console? The latter is probably more useful for posterity. You should probably check if the resolved path logged in the console looks correct.

I'll close the issue, but obviously if something crops up reopen/open a specific issue.

**Comment by starper** [comment]
I mean popup message. I've just restarted server with console open and everything seems to be correct.
