### ISSUE TITLE
Autocomplete doesn't suggest all local identifiers

### ISSUE THREAD

**Issue by smith-kyle** [nwolverson/atom-ide-purescript#130]
#### .js file

![image](https://cloud.githubusercontent.com/assets/5474861/19453744/598eb2dc-946b-11e6-8312-7b3335dcaee3.png)
#### .purs file

![image](https://cloud.githubusercontent.com/assets/5474861/19453864/d3eaa6c6-946b-11e6-90a9-ff4e829a5844.png)

It'd be nice to have autocompletion for all local identifiers

**Comment by nwolverson** [comment]
`myKey` isn't a valid identifier where you are typing there?

Completions are suggested from top level identifiers currently, per psc-ide support, ideally they would be suggested for all identifiers in scope if we can get support for that down the line (this is restricted to identifiers saved in externs files for performance). But I hadn't in mind to enable the default purely text-based completion, in my experience previously that just gives noise.

We can stop suppressing that if my opinion isn't popular.

**Comment by smith-kyle** [comment]
I understand that this is a preference thing and might not work for some people. Is that something we could see as a toggle in the package settings?

**Comment by nwolverson** [comment]
Yes, for sure that should be no problem.
