### ISSUE TITLE
`do` keyword does not appear in auto-complete list

### ISSUE THREAD

**Issue by dkoontz** [nwolverson/atom-ide-purescript#131]
![image](https://cloud.githubusercontent.com/assets/7493/19454025/7a736ae6-946c-11e6-9b2b-c6e3cf8fcd06.png)

All the rest of the keywords look good, but do is missing.

**Comment by nwolverson** [comment]
Closing as this is from language-purescript, copied to linked issue

**Comment by nwolverson** [comment]
@dkoontz should be there now!

**Comment by dkoontz** [comment]
Thanks!
