### ISSUE TITLE
Autocomplete and quick fix wont work

### ISSUE THREAD

**Issue by Fresheyeball** [nwolverson/atom-ide-purescript#133]
So, I was using **ide-purescript** and loving it, when some of its nicer features just stopped working. Notably:
- autocomplete
- quick fix
- type inspection

Seem to have given up the ghost. Things I've tried:
- `rm -rf ~/.atom`
- `rm -rf ~/.config/Atom`
- upgrading atom
- updating ide-purescript
- pursuit search
- other's I may not have noticed yet

Right now there are no errors shown in the atom developer console and I'm at a loss.

![image](https://cloud.githubusercontent.com/assets/609279/19627777/66f1de0e-990c-11e6-90ce-61d16be8fd3d.png)

I'm running Ubuntu 14.04 with 

``` yaml
$ atom --version
Atom    : 1.11.2
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0
```

and ide-purescript `0.14.10`.

The _Restart Psc Ide_ command also does not seem to have any observable effect. Beyond...
![image](https://cloud.githubusercontent.com/assets/609279/19627800/f1700d76-990c-11e6-8980-4c73b20bb085.png)
![image](https://cloud.githubusercontent.com/assets/609279/19627802/f8bb7cfa-990c-11e6-8dca-c6e47295b62d.png)

**Comment by nwolverson** [comment]
Hi, seems there is a problem connecting to `psc-ide-server`.  Oddly it seems like there is a failure to resolve `localhost`, maybe there is some network issue (at least inside Atom)?

Just to pin things down you can try the following:
- Close Atom
- `echo -n 1234 > .psc-ide-port` (in your project dir)
- `psc-ide-server --debug -p 1234`
- Open atom in your project dir

Don't know why quick-fix would fail, at least if it is for e.g. imports it should work if the build works (you have the squiggly underlines)

**Comment by nwolverson** [comment]
You might want to look and see if this could be the same as https://github.com/nwolverson/atom-ide-purescript/issues/115 if you've had some network change since this worked previously

**Comment by Fresheyeball** [comment]
Ok. So I worked through this. My hosts file was all borked for some reason. Fixing the hosts file resolved the problem! So nothing to do with ide-purescript. I don't know how that happened. Sorry for bugging you, ide-purescript was just the first symptom of a system problem.
