### ISSUE TITLE
Default build command 'pulp build --no-psa --json-errors' fails

### ISSUE THREAD

**Issue by rollandjb** [nwolverson/atom-ide-purescript#136]
I am a `prescript, pulp, atom` etc newbie, so please excuse stupid questions.

What is the difference between `Build on save` and pressing `ctrl-o b`?

- `Build on save` works irrespective of what's set as the `Build command`, even `gobbledygook`.

- The default build command `pulp build --no-psa --json-errors` fails for `ctrl-o b`with `Error running PureScript build command: Error: Didn't find JSON output at Object.exports.error ...`

- On the command line, `pulp build --no-psa --json-errors` fails with `Error: Unrecognised arguments: --json-errors`

`pulp` documentation says parameters to be passed through to `psc` compiler must be separated from `build` options with `--`.

Thus `pulp build --no-psa -- --json-errors` works for `ctrl-o-b` and command line.

I have `pulp` version 10.0.0, `psc` version 0.10.2 and `ide-purescript@0.14.10`.

Thank you

Rolland

**Comment by clojj** [comment]
pulp build --no-psa **-- --json-errors** 

..works for me too
So I guess this could be a typo or missing change in the plugin's settings (?)

**Comment by kritzcreek** [comment]
I think this is happening because of the recent changes in pulp's 0.10 release with regards to command line arguments: https://github.com/bodil/pulp/blob/master/CHANGELOG.md#1000

**Comment by rollandjb** [comment]
That certainly explains that. Thank you.

What does `Build on save` use as a build command? It seems to work irrespective of what is in the build command. I'm probably missing something.

**Comment by kritzcreek** [comment]
@rollandjb `Build on save` uses the running psc-ide-server instance to recompile the currently edited module. It's a different kind of build though. As an example consider the following module structure:

`C -> B -> A`

here `C` depends on `B` and `B` depends on `A`.

You now make a change inside `B` that causes type errors inside `B` and `C`.

`Build on Save` will only report the type errors inside `B` though and not the ones in `C`.

The "full build" through pulp can also do bundling etc. `Build on save` is primarily used for near instant feedback in the editor.

**Comment by nwolverson** [comment]
Thanks for reporting, guess I'll update the default (and break it for anyone that hasn't updated pulp!)

**Comment by rollandjb** [comment]
**@nwolverson** No problem!

**@kRITZCREEK** Thanks for the explanation.

**Comment by nwolverson** [comment]
Updated this default - if you find your build command now fails for the opposite reason, upgrade `pulp` or set an explicit build command.
