### ISSUE TITLE
windows 10 can't get psci to work

### ISSUE THREAD

**Issue by theGhostJW** [nwolverson/atom-ide-purescript#137]
Hi
from the windows command prompt
C:\SourceCode\Purescript\PurescriptByExample\functions-and-records>C:\Users\thegh\AppData\Roaming\npm\pulp.cmd psci
or
pulp psci

all work but when I launch <Purescript><PSCI: Open> from atom I get an empty pane and the text box which is editable but the text does not go anywhere when <ctrl><enter>; <shift><enter> or <enter> is hit.

have tired

C:\SourceCode\Purescript\PurescriptByExample\functions-and-records>C:\Users\thegh\AppData\Roaming\npm\pulp.cmd psci;
pulp psci
and
pulp.cmd psci 

none seem to work.

John

**Comment by nwolverson** [comment]
1. What do you mean "when ; or is hit" - I don't think semicolon means anything in particular, and it looks like you misworded something. Did you try writing an expression in the input box and pressing enter/return?
1. When you say various commands work and then don't work (eg "pulp psci") - do you mean this workson the command prompt but not when set as the psci command?
1. I presume you do not see "PSCi, version ..." ?

**Comment by nwolverson** [comment]
Just checked this still works for me on windows 10 with latest everything, but psci is *really* slow to start now. 

Are you starting PSCI from within a purescript project in atom? You may need to open a `.purs` file and then open PSCI from there.

Lastly have a look at the developer tools/console to see if any errors appear.

**Comment by theGhostJW** [comment]
OK thanks - working now had started atom in a parent directory and running the command line from the the project directory -> *user error*.

I notice if i try the same trick from the command line pulp psci gives me:
* ERROR: No bower.json found in current or parent directories. Are you in a PureScript project?

Would it be possible for such errors to be piped through to the psci display panel when someone makes this sort of mistake?

**Comment by nwolverson** [comment]
Yup that looks like some bad error reporting, sorry!
