### ISSUE TITLE
Error rebuilding file that has been renamed

### ISSUE THREAD

**Issue by nwolverson** [nwolverson/atom-ide-purescript#140]
Created a file, renamed it, did a full build. Afterwards fast rebuild still seemed to be trying to build a non-existent file (also this causes psc-ide to exit rather than returning an error response...)

Closing and re-opening the file fixed things

**Comment by kritzcreek** [comment]
Thanks for spotting this, I'll make a ticket over at the ps repo

**Comment by nwolverson** [comment]
Fixed 021da1f33fc2cb7aef3c4e5df2808e4327fb0f48
