### ISSUE TITLE
Entering text in the import dialogue triggers JS error

### ISSUE THREAD

**Issue by mrmurphy** [nwolverson/atom-ide-purescript#143]
@nwolverson thank you so much for all of the time and effort you have put in on this. It's super duper cool wunderbar.

I'm getting a JS error when I type in the text field that seems like it's supposed to filter the potential import list. Here's a gif of what it looks like:

![kapture 2017-01-16 at 16 31 14](https://cloud.githubusercontent.com/assets/1227109/22002469/82f8e5ee-dc09-11e6-8f5a-ab4ed5a20456.gif)

Again, thanks!

**Comment by nwolverson** [comment]
Looks like this was the fix typo command? At least doesn't seem to be either of the two specific import commands. Should be fixed now I think (next release)

**Comment by mrmurphy** [comment]
This was on "Add specific import". Thanks for fixing, I'll install master and check it out!

**Comment by mrmurphy** [comment]
@nwolverson I just pulled down to test and now nothing comes up at all when I trigger either of the import commands. There are no JS errors in the console, either.

**Comment by nwolverson** [comment]
There is "Add module import" and "Add explicit import", did you mean the latter? But that doesn't have the UI you screen-shotted. (Are you running a command from the command palette or some other means?)

**Comment by mrmurphy** [comment]
whoops, yes, I meant "Add explicit import" which (before this latest update) brought up a text box where I could type the name of a symbol. After hitting enter, that text box would turn into the autocomplete list screenshotted above and show all modules with that symbol available.

One of those options could be selected, and then that module and symbol would be added to the file imports.

**Comment by nwolverson** [comment]
Ah, that explains it, wasn't looking at the 2nd level menu.

Can you try again, I just published the update - it wasn't built.

**Comment by mrmurphy** [comment]
Nice! I just tried it out, and the 2nd menu does come back up, and the JS error is gone, but autocompletion doesn't do anything:

1. Trigger "Add explicit import"
2. Type `#`
3. In the 2nd dialogue hit the letter `P`, which should narrow the list to `Prelude`
4. Observe that all options are removed.

**Comment by nwolverson** [comment]
Sorry, the filtering is on the identifier which is all the same! Not so useful. 

One more try 021da1f33fc2cb7aef3c4e5df2808e4327fb0f48

**Comment by mrmurphy** [comment]
Brilliant!
