### ISSUE TITLE
After an import is added, the editor looses focus

### ISSUE THREAD

**Issue by mrmurphy** [nwolverson/atom-ide-purescript#144]
Here I am with another one.

After using the import tool to add a new import (the `Add Explicit Import` command) the editor loses focus, and I can no longer type in my editor window, nor can I trigger another import with my vim keybindings until I either click back into the editor, or use some hack like opening and closing the tree view with the keyboard.

Thanks a billion!

**Comment by nwolverson** [comment]
Oops.

(Not sure if you've found that autocomplete can add imports without running an explicit command, but that's another way of doing it).

**Comment by mrmurphy** [comment]
@nwolverson Are you referring to import from autocomplete? Or module import? As far as I know neither of those support importing symbols, like `.?`, `<<<`, and `<*>`. But I can do that through `Add Explicit Import`. And that's mostly what I use it for.

**Comment by nwolverson** [comment]
Ah, that sounds just right, that's exactly what I'd use it for. Carry on...

**Comment by mrmurphy** [comment]
Brilliant! I was just checking to see if I could save you some work and submit a PR, but you beat me to it.
