### ISSUE TITLE
Is the Alt-Enter keyboard shortcut for quickfixes intentionally missing on Windows?

### ISSUE THREAD

**Issue by garyb** [nwolverson/atom-ide-purescript#146]
I'm not sure if this is by design or not. I'm pretty sure it used to work, but I've had to add it to my local keymap to make it work now.

**Comment by nwolverson** [comment]
Nope, think that is an omission when changing the prefix on windows. It doesn't conflict with anything does it?

**Comment by garyb** [comment]
It appears to be unbound in the default keymap as far as I can tell. I've not had any problems since adding it back myself either... I'll make a PR :)
