### ISSUE TITLE
Autocomplete and primitive types, as well as the '=' symbol

### ISSUE THREAD

**Issue by Bellarmine-Head** [nwolverson/atom-ide-purescript#152]
PureScript... a joy.  Editing in Atom.io (on Windows 7) is also a joy.  Thank you.

Re. atom.io, a very common thing for me - it happens _all_ the time - is to type a `=`, hit enter for a new line, and get `=<<` inserted because of auto-completion.  The screenshot illustrates why:-

![s1](https://cloud.githubusercontent.com/assets/3470891/23753451/7545fb6c-04d1-11e7-8d72-950a05e7c7c6.png)

Related to this is typing the names of primitive types, e.g. `Int` and `Boolean`, and getting wonky insertions and - worse - erroneous module import additions, which I then have to go and explicitly undo.  This has become such a pain that I had to uncheck the `Add import on autocomplete` option... which is sad because that would be a very useful option to have enabled, since PureScript's import system is so granular.

The following screenshots illustrate re. `Int` and `Boolean`.

![s2](https://cloud.githubusercontent.com/assets/3470891/23753610/091a0838-04d2-11e7-96b6-f638c976efb0.png)

![s3](https://cloud.githubusercontent.com/assets/3470891/23753613/0ce29ee4-04d2-11e7-90b2-eb2d4b126def.png)

My suggestion is that primitive types, and primitive symbols like `=`, are always included in the auto-completion lists (at the top).

My apologies if there is already a way to configure this... I did look through the settings of both atom purescript packages, but didn't see anything obvious.

**Comment by Bellarmine-Head** [comment]
I ameliorated the situation by changing a setting in the `autocomplete-plus` core package to autocomplete on `tab` instead of `enter`; more specifically:-

![s4](https://cloud.githubusercontent.com/assets/3470891/23754428/d9c880ac-04d4-11e7-9881-e4119e28acc7.png)

This has allowed me to re-enable `Add import on autocomplete` for PureScript editing.

Good stuff!  I'm glad I took the time from coding to investigate this and improve things.

But I still think it would be worth it for the `atom purescript` package to include these primitives in its autocomplete lists.

**Comment by Bellarmine-Head** [comment]
While I'm on the subject, here is another setting I made a while ago in `autocomplete-plus` that improves autocomplete wrt PureScript...

![s5](https://cloud.githubusercontent.com/assets/3470891/23754677/c7c0eb0a-04d5-11e7-88ba-53bd0d9039df.png)

As you might expect, it stops autocomplete lists popping up while you're editing strings and comments.

**Comment by nwolverson** [comment]
Primitive types are now completed via the IDE server as of 0.18.1 4d440cdfd49ea6fe7321bfb64d3222a600400c64 - purescript/purescript#2925
