### ISSUE TITLE
Linter v2

### ISSUE THREAD

**Issue by starper** [nwolverson/atom-ide-purescript#153]
It seems like `ide` is not compatible with new version of [linter](https://github.com/steelbrain/linter)

**Comment by Bellarmine-Head** [comment]
I see that `linter` is offering an update to 2.0.0, so I will stick with 1.11.23 for the time being.

What goes wrong with the new version wrt to `atom-ide-purescript`?

**Comment by starper** [comment]
@Andrew-Webb There were no any errors or warnings shown in `v2.0`. But with `v2.1` everything works fine. So I guess it was `linter`'s bug, not `ide`'s. Sorry for the false alarm :)

**Comment by nwolverson** [comment]
Let me know if you do see any further issues, I think we're maybe using an internal API so things could indeed break
