### ISSUE TITLE
QuickFixes broken with linter 2.0

### ISSUE THREAD

**Issue by born2defy** [nwolverson/atom-ide-purescript#154]
Using current version of Atom and atom-ide-purescript along with pulp@0.10.7 and psc@0.10.7 on a windows 7 machine.  When trying to use the QuickFixes feature nothing happens.  This is when evoking it through the keymap or directly through the Atom menu.  It used to work fine in previous version so I'm not sure what may have changed.

**Comment by nwolverson** [comment]
Sorry not had time to try reproduce this. Would be useful to note the particular Atom version (for posterity if nothing else) and a sample issue which you are attempting to use the fix on (e.g. is it a specific kind of import quickfix?)

**Comment by born2defy** [comment]
Sure - Atom version = 1.15.0.  The issue is happening on import quickfixes with unused references.  Instead of removing the unused references, no action is taken at all.  I tried to check the logs, but it doesn't look like anything is logged when a quickfix action is taken.

**Comment by nwolverson** [comment]
Looks to be related to linter update. As a workaround right now, you can probably downgrade the atom-linter version - or maybe use pscid to apply fixes (or purescript-suggest).

The good news is that the linter updates bring some cool new stuff, that should let me delete code and have a better UX after updating - in particular https://github.com/steelbrain/intentions

**Comment by born2defy** [comment]
Correct - downgrading Linter resolved the issue.

**Comment by nwolverson** [comment]
I'm working on this now, can hopefully release something this weekend that (only) works with the new Linter.

**Comment by nwolverson** [comment]
Done. Linter 2.0 will now be required, but giving a better UI https://github.com/nwolverson/atom-ide-purescript/releases/tag/v0.16.1
