### ISSUE TITLE
Support for purescript v0.11 consolidated executable

### ISSUE THREAD

**Issue by adicirstei** [nwolverson/atom-ide-purescript#158]
starting with [v0.11.0](https://github.com/purescript/purescript/releases/tag/v0.11.0) purescript ships with one consolidated executable. That means the `psc-ide-server` can no longer be found in path.

![image](https://cloud.githubusercontent.com/assets/1694688/24899961/e9d5e152-1eaa-11e7-9ada-1151cf3fc68b.png)

Please add support for the new executable.
Thanks!

**Comment by nwolverson** [comment]
Please see release notes https://github.com/nwolverson/atom-ide-purescript/releases/tag/v0.17.0 - this is configured via "Use combined executable" setting, as calling convention is different and either new or old version may be somewhere in your path.

(Note that "psc-ide-server" text may still be found, but the text should then read "Looked for: purs in PATH": in this case)

Please raise an issue if there are any problems with this.

**Comment by adicirstei** [comment]
Oh! I didn't noticed that option down there. 

Thanks a lot and sorry! You did an amazing job.
