### ISSUE TITLE
Linter 2.1.3 Error

### ISSUE THREAD

**Issue by born2defy** [nwolverson/atom-ide-purescript#159]
The latest version of Linter introduces a change which now produces this error when building from ide-purescript:  cannot read property setAllMessages of undefined.

**Comment by nwolverson** [comment]
Thanks, can reproduce. Actually seems to be a linter bug which is being fixed https://github.com/steelbrain/linter/pull/1434

**Comment by born2defy** [comment]
That's what I figured - just wanted to alert you though.

**Comment by steelbrain** [comment]
Sorry for the trouble everyone, Linter v2.1.4 is out

**Comment by nwolverson** [comment]
@steelbrain while you're here, thanks for the work on Linter and related packages, it's a big step forward with the 2.0 changes
