### ISSUE TITLE
Lint messages are cached

### ISSUE THREAD

**Issue by garyb** [nwolverson/atom-ide-purescript#164]
I'm not sure if there's anything you can do about this, or whether it's a problem with linter, but if you write something like this:

``` purescript
f a b = ?x
```

You'll get a message with the inferred type `t0`, etc. If you then change it to this:

``` purescript
f a b = ?x a b
```

The message stays the same. You have to change the hole to get the new message:

``` purescript
f a b = ?x' a b
```

Now the message updates correctly with the inferred type `t0 -> t1 -> t2`.

There are a few errors this will occur frequently with (imports, decls with missing types, etc.) but the behaviour with holes is the most infuriating. :smile:

Perhaps there's some way to force the message through if it is indeed linter that is the issue here, just adding a timestamp or an incrementing id or something to make it invalidate correctly.

**Comment by nwolverson** [comment]
Odd, I assume this is just with quick rebuild and saving the one file after each change? Not something I remember seeing around imports, but I didn't tend to use holes that much.

Thanks for the specific example, I'll look into it when I get back from holiday :)

**Comment by garyb** [comment]
>  I assume this is just with quick rebuild and saving the one file after each change? 

Yeah, that's right.

> Not something I remember seeing around imports

The case I'm thinking of is where you have an explicit list of imports that has unused imports, and then you edit the file making yet more of the imports in that list unused. Something like that anyway!

> I'll look into it when I get back from holiday

Enjoy! :smile:

If I get a chance before you get back I might take a stab at it too. I currently know nothing about how any of this works though. :wink:

**Comment by nwolverson** [comment]
I was just replying to say this seems to work with your example, but actually I can reproduce it so long as when I add the `a b` I don't do so with the cursor to the immediate right of the hole, which has the effect of moving the squiggle range.

So seems to be something that happens when the squiggle doesn't move, investigating further.

**Comment by nwolverson** [comment]
The linked issue is resolved, though with atom-ide-ui linter need not be used; regardless tested with the above example and still seems fine now.
