### ISSUE TITLE
QuickFixes broken with linter 2.2

### ISSUE THREAD

**Issue by born2defy** [nwolverson/atom-ide-purescript#165]
This is a re-occurrence of a previous issue, which had been related to Linter.  On Windows 7, quick fixes simply don't do anything when the command is triggered (either by shortcut or menu).  Here are the relevant specs:

Atom: 1.18.0
Linter: 2.2.0
Linter UI Default: 1.6.2
Ide Purescript: 0.18.0

**Comment by gabejohnson** [comment]
Same stats, same problem on macOS 10.12.5

**Comment by born2defy** [comment]
That is odd, as I have the exact same setup running on macOS 10.10.5 and QuickFixes works perfectly.

**Comment by nwolverson** [comment]
Also works for me on mac, same versions (tested with quick fix for explicit import). Can you check the console for errors & your `purs` version (which may be in node modules depending on your setup). Thinking maybe @born2defy has different PureScript version on the mac vs windows machine if atom package versions are the same?

**Comment by born2defy** [comment]
For me, both Mac and Windows are using the same exact `purs` version of 0.11.5.  Checked the console but nothing is logged when ShowQuickFixes is selected from the context menu.  Besides the operating system, everything else is identical between the two set ups.  Except that the quickfixes just fail silently on Windows.

**Comment by born2defy** [comment]
Just to add to this, I recently set up a brand new macbook with the identical set up as the other 2 systems, and everything works perfectly.  It is only the windows system that is having failures with ShowQuickFixes.

**Comment by nwolverson** [comment]
Closing this as the Linter UI is no longer used, so the non-showing of its menu isn't relevant.

If there's a corresponding issue still (ie wasn't to do with linter but with actually applying the fix) please do reopen.
