### ISSUE TITLE
Atom IDE

### ISSUE THREAD

**Issue by paulyoung** [nwolverson/atom-ide-purescript#172]
I'm not familiar enough with the internals of this project to know how much this affects things, but it seemed worth starting a discussion.

Atom just [introduced Atom IDE](http://blog.atom.io/2017/09/12/announcing-atom-ide.html) which provides the [Atom IDE UI](https://nuclide.io/blog/2017/09/12/Introducing-Atom-IDE-UI/).

> It extracts only the subset of the core UI features from Nuclide necessary to support Atom’s [atom-languageclient](https://github.com/atom/atom-languageclient) library in displaying features supported by the [language server protocol](http://langserver.org/).

@kRITZCREEK and I discussed this briefly [on Twitter](https://twitter.com/py/status/841130571623419905) a while ago. Christoph said:

> already commented in the thread, language server for psc-ide is possible, just needs a different "frontend" for the backend

> but the "reach" it promises is basically vscode right now

It seems like that reach has now increased to Atom.

**Comment by nwolverson** [comment]
Yup, I'd like to move towards using the LSP server (which [already exists](https://www.npmjs.com/package/purescript-language-server)) but need to find out what the gaps will be, decide an approach to fill in the gaps, and look at what degradation of existing functionality there will be.

It may be that there is also an advantage for using some of the individual UI features before moving the whole way there (eg datatips could be a win).

I'd like to prototype this out on a branch and see how it works out.

**Comment by nwolverson** [comment]
This is looking already pretty promising, I have tooltips, autocomplete, diagnostics, code actions... I'll publish a test version soon to try on the beta channel

**Comment by nwolverson** [comment]
If anybody wants to try this out, there is a preview available if on the atom-beta channel - `v0.19.0-lsp1` - since `apm` tags don't work as I hoped this will install automatically if you're on beta channel. There are many missing things.

**Comment by safareli** [comment]
@nwolverson my atom version is 1.21.0 (it's not beta) but when i installed ide-purescript I got version  `0.19.0-lsp1` so looks like everyone who installs it will get the beta version instead.

**Comment by safareli** [comment]
This will fix the issue if someone has it:

```
$ apm remove ide-purescript
Uninstalling ide-purescript ✓
$ apm install ide-purescript@0.18.0
```

**Comment by nwolverson** [comment]
Oops, looks like I didn't set the correct bounds on the prerelease version to target the beta channel - unfortunately apm works kinda like npm but has a more simplistic idea of version numbering, I'll push a fix release tonight.

**Comment by nwolverson** [comment]
Think I'm going to try and move to the language server  and atom ide once I can do a few more pieces and get some volunteer(s) to test, need to figure out how to handle the transition (thinking of users who do not have atom-ide already, is there some way to prevent a "things just stopped working" scenario).

**Comment by nwolverson** [comment]
This is now in a testable state in case someone would like to be a guinea pig (@paulyoung?)

```apm install ide-purescript@0.19.0-lsp3```

Requires atom-ide-ui but otherwise should work as before

**Comment by paulyoung** [comment]
@nwolverson thanks for the heads up.

I use spacemacs these days but I'm happy to give this a try and report back.

I'm traveling at the moment so it might take me a couple of days.

**Comment by born2defy** [comment]
I am trying it out right now on Windows 7, and it doesn't appear to start the ide-server when a .purs file is opened, which makes everything else stop functioning.

**Comment by nwolverson** [comment]
Uh, looks like I maybe accidentally require 0.11.7, could it be that ? :)

**Comment by born2defy** [comment]
I don't think so as that is the version I am using.  I have it installed locally using npm - could that be the issue?  Maybe the new version isn't using the BIN directory like it's supposed to?  The option was checked when I tried the new version, but maybe it isn't implemented correctly?

**Comment by paulyoung** [comment]
`0.19.0-lsp3` did not work for me. There was no "Started IDE Server (port ...)" message, there were no tooltips available, and no errors when writing incorrect code (and then saving).

However, the Atom "Installed Packages" UI said that I could upgrade to `0.19.1` which works as expected.

macOS High Sierra
Version 10.13.2 (17C88)

Atom 1.23.1 x64

**Comment by nwolverson** [comment]
@paulyoung 0.19.1 is irrelevant to this discussion, as it is basically the existing package. But sounds like you maybe have the same issue, though impossible to tell without more info.

I'll hopefully get a chance to fix this issue and maybe ask for another guinea pig this weekend...

**Comment by paulyoung** [comment]
I didn't install `atom-ide-UI`. Could that be it? 

Other packages prompted me to install dependencies, so I sssumed I would see something if I didn't already have it.

**Comment by nwolverson** [comment]
As noted requires `atom-ide-ui`, I'm tending towards installing that as a dependency when this is pushed out for real (though was slightly concerned if it was a bit pushy), but it isn't yet.

Regardless, the lack of `atom-ide-ui` affects just the more obvious UI components - startup of the IDE server is a separate issue.

**Comment by loganmac** [comment]
@nwolverson I installed it (0.19.1) to play around. It's working great for me! At least everything I've tried so far.

**Comment by nwolverson** [comment]
I've now pushed this out as the new version. Hopefully the above issues are fixed, certainly some are. Please raise new specific issues if any issues observed with the latest version (0.20+)
