### ISSUE TITLE
Atom core deprecation notification

### ISSUE THREAD

**Issue by winksaville** [nwolverson/atom-ide-purescript#173]
Newbie to Atom and PureScript so this very likely is a configuration/install problem on my part but I'm getting a "Deprecation" warning and below is the "Deprecation Cop" output:
```
The contents of atom-text-editor elements are no longer encapsulated within a shadow DOM boundary. Please, stop using rootElement and access the editor contents directly instead.
HTMLElement.rootElement - /usr/lib/atom/src/text-editor-element.js:23:10
getFromShadowDom - /home/wink/.atom/packages/ide-purescript/node_modules/hover-tooltips/lib/hover-tooltips.js:16:19
attach - /home/wink/.atom/packages/ide-purescript/node_modules/hover-tooltips/lib/hover-tooltips.js:26:22
<unknown> - /home/wink/.atom/packages/ide-purescript/node_modules/hover-tooltips/lib/hover-tooltips.js:125:13
Workspace.observeTextEditors - /usr/lib/atom/src/workspace.js:768:9
ToolTipProvider.activate - /home/wink/.atom/packages/ide-purescript/node_modules/hover-tooltips/lib/hover-tooltips.js:122:43
```

**Comment by nwolverson** [comment]
This could be reported on https://github.com/ranjitjhala/hover-tooltips which is the source of this issue (though it is indeed being used by this plugin).

Not worth caring about for now, this can be replaced with atom-ide-ui's [datatips](https://github.com/facebook-atom/atom-ide-ui/blob/master/docs/datatips.md) so this dependency can be removed soon.

**Comment by nwolverson** [comment]
This should be resolved via the latest changes to stop using `hover-tooltips`
