### ISSUE TITLE
Autocomplete duplicates names ending in prime

### ISSUE THREAD

**Issue by MonoidMusician** [nwolverson/atom-ide-purescript#178]
Thanks for the update, it's super cool! Just found a bug though: Typing `Lens'` and then enter results in the autocompletion `Lens'Lens'`, so I think something with identifying identifiers and doing the replacement might be wonky. (I don't think I've seen this happen before the update, but I don't know exactly what changed.)

**Comment by MonoidMusician** [comment]
Update: `Lens'|s'` does not seem to trigger the bug, if there are matching characters after the cursor (`|`) when I hit enter to autocomplete.

**Comment by nwolverson** [comment]
This seems to work fine for me completing either with qualifier or without:
![prime-completion](https://user-images.githubusercontent.com/2770891/34542060-ca8d49fc-f0d2-11e7-9619-0663194dc726.gif)

**Comment by MonoidMusician** [comment]
I think it only happens when the previous character is already a non-word character. So type out `F.Foo'` and then press enter. Also seems to happen with operators like `^.`, which might be easier to reproduce. And autocompleting import modules also fails to delete what I’ve already typed if it contains a `.`.

**Comment by nwolverson** [comment]
Can you make sure you have the latest version? The import modules case I fixed just recently, it used to only replace up to the previous `.` but now should properly replace the whole module name

**Comment by MonoidMusician** [comment]
Ah, right :) That works, thanks!

**Comment by nwolverson** [comment]
Sorry, just to clarify, you tried the same thing with the latest version and it seems to work?

**Comment by MonoidMusician** [comment]
Yes!
