### ISSUE TITLE
Remove old `goto-definition` command

### ISSUE THREAD

**Issue by garyb** [nwolverson/atom-ide-purescript#180]
I know we talked briefly about this on Slack, but thought I'd open an issue to discuss further.

I don't really like relying on mousey activation of this as I use a lot of mouse selection stuff already, so, for instance, if I want to select a word in a few places I'll hold ctrl & double click the things I want to select - that doesn't really work when ctrl+click also does goto definition. I also have some other modifiers so that alt/ctrl are also used for selectiony things, so I'd have to rebind it to something like ctrl+alt+shift+click which is not super convenient :wink: so it would be nice to have the old `goto-definition` command restored, if possible.

If that's not going to happen, then this issue could be taken as pointing out there's a few things that need updating to remove actions for the old command instead:

- https://github.com/nwolverson/atom-ide-purescript/blob/0c4e01ab8327ccac53716017cec6dfed65109a58/menus/menus.cson#L44-L47
- https://github.com/nwolverson/atom-ide-purescript/blob/6c8d12c277cdbdf2ae53f8a1f649812526f887df/keymaps/core.cson#L15
- https://github.com/nwolverson/atom-ide-purescript/blob/6c8d12c277cdbdf2ae53f8a1f649812526f887df/keymaps/core.cson#L29
- https://github.com/nwolverson/atom-ide-purescript/blob/b8aeb24481fbb72292d63bf938b9d5801a97c9ca/package.json#L29

**Comment by garyb** [comment]
Ok, I have a kinda workaround - you can use ctrl+alt+enter on a selection to activate hyperclick too - so I've bound the click to the ctrl+alt+shift claw, and will just not use it :wink:

The latter point stands though, as those actions appear in the UI but do nothing.

**Comment by nwolverson** [comment]
It's easy enough to restore the old behaviour, but I wonder if it's the right thing, as this is really more general behaviour from hyperclick that was just being rewrapped.

As you've just found, the command is `hyperclick:confirm-cursor` which by default is ctrl+alt+enter (mac: cmd+alt+enter)

**Comment by nwolverson** [comment]
Removed and updated docs a little.
