### ISSUE TITLE
Applying suggestions always inserts a newline too

### ISSUE THREAD

**Issue by garyb** [nwolverson/atom-ide-purescript#185]
At least it does on Windows in a file with `LF` line endings, I wouldn't be surprised if there's some platform nonsense going on here.

**Comment by nwolverson** [comment]
I think this is maybe just https://github.com/nwolverson/purescript-suggest/issues/7 - is this where applying a remove import leaves a blank line instead? Sounds like not the same as https://github.com/nwolverson/vscode-ide-purescript/issues/75 if you have `LF`.

**Comment by garyb** [comment]
Hah, no, it's different to either of those actually - the most prominent case is import related, but it's where the imports are updated (redundant imports from the module, not that the import is entirely redundant). It adds a new empty line under the import that is rewritten, rather than at the end of the buffer too.

**Comment by nwolverson** [comment]
Can you retest this with latest, there should be some relevant changes

**Comment by garyb** [comment]
Works a treat now 😍

**Comment by nwolverson** [comment]
Great :)
