### ISSUE TITLE
Add clause/Case split oddities

### ISSUE THREAD

**Issue by unthingable** [nwolverson/atom-ide-purescript#187]
Doesn't do what it says...

"Add clause" on the type declaration:

```purescript
toInt :: Int -> Array Int -> Maybe Int

toInt ( _ :: Int) ( _ :: (Array Int)) = ?toInt
```

(extra newline and extra type hints)

Then, case splitting on the second `_` and typing `Array Int`:

```
Error: Request workspace/executeCommand failed with message: Found a non-type-declaration at new ResponseError (/Users/alexk/.atom/packages/ide-purescript/node_modules/vscode-jsonrpc/lib/messages.js:46:28) at handleResponse (/Users/alexk/.atom/packages/ide-purescript/node_modules/vscode-jsonrpc/lib/main.js:430:48) at processMessageQueue (/Users/alexk/.atom/packages/ide-purescript/node_modules/vscode-jsonrpc/lib/main.js:258:17) at Immediate. (/Users/alexk/.atom/packages/ide-purescript/node_modules/vscode-jsonrpc/lib/main.js:242:13) at runCallback (timers.js:651:20) at tryOnImmediate (timers.js:624:5) at processImmediate [as _immediateCallback] (timers.js:596:5)
```

Atom 1.23.3
```
$ pulp --version
Pulp version 12.0.1
purs version 0.11.7 using /usr/local/bin/purs
```
atom-ide-ui 0.8.1
ide-purescript 0.21.1
language-purescript 0.8.3

**Comment by nwolverson** [comment]
Re newline - https://github.com/nwolverson/purescript-language-server/issues/1

Type hints - yes I don't think that's the right decision

Some oddity if I split on (_ :: Int) even with the correctly selected range

The last issue - this should not work, `Array` is not an ADT, I think it's fine in this case that you can find the details in the output window.

**Comment by unthingable** [comment]
Re splitting on an ADT: ah, that makes sense. I tried replacing Array with List and Maybe, which are ADTs, with the same error.

FWIW, trying the same in emacs works fine (with List and Maybe, for Array it prints "Not found"), without newline or extra type hints. In VSCode the behavior is the same as Atom (extra newline, type hints).

**Comment by nwolverson** [comment]
"replacing Array with List and Maybe" - you mean typing "Maybe Int" in the popup? That does seem to work fine for me. 

The error you show "Found a non-type-declaration" appears to be the result of "add clause" where you want to "case split"

**Comment by unthingable** [comment]
I meant replacing `Array Int` with `Maybe Int` in the type signature and then typing "Maybe Int" in the popup.

Oops. :) Yes, using the correct command works, sorry. Same oddity though:

```purescript
toInt :: Int -> Maybe Int -> Maybe Int
toInt base _ = ?toInt
```

case splits to:

```purescript
toInt :: Int -> Maybe Int -> Maybe Int
toInt base Nothing = ?toInt

toInt base (Just ( _ :: Int)) = ?toInt
```

**Comment by nwolverson** [comment]
Can you try again with latest release, I've made some changes but not sure if I hit all these points

**Comment by nwolverson** [comment]
Closing for lack of reply
