### ISSUE TITLE
Duplicate Module Name Fails in Silence

### ISSUE THREAD

**Issue by AlexMouton** [nwolverson/atom-ide-purescript#189]
Hi Nick, and all.

Just noticed that when I copy paste a file, in a plan to split one module into two, and fail to rename either one, The build task fails silently, but gives the expected error in pulp.

Thanks for making these nice tools for us!

Alex

**Comment by nwolverson** [comment]
I guess this is one of the errors without source locations

**Comment by nwolverson** [comment]
It is https://github.com/purescript/purescript/issues/3208

**Comment by nwolverson** [comment]
Closing as this should be fixed with purs 0.12
