### ISSUE TITLE
fast rebuild stopped working

### ISSUE THREAD

**Issue by joopringelberg** [nwolverson/atom-ide-purescript#192]
All of a sudden, files are no longer rebuilt on saving changes to them (I checked the output directory, observing no changes to the compiled .js files). Hence, no errors are detected etc. No errors are thrown. There is a 'purs ide server' process running after opening atom that shuts down after closing atom. A full build succeeds and then I'll get the usual feedback.
I unchecked and re-checked "Use fast rebuild", restarted atom, restarted my mac, but nothing changes.
I have not installed any new packages nor changed anything else in atom.
Configuration:
- default build command: pulp build -- --json-errors
- auto-start IDE server is on
- no IDE server port specified
- psc-ide-server executable location is default: psc-ide-server
- purs location is default: purs
- use combined executable is checked.
I can't think of anything to do. 
Thanks in advance!

**Comment by joopringelberg** [comment]
I removed the bower_components directory and ran bower install. That fixed the issue. Can't think why, though. I also reinstalled purescript-language and purescript-ide, but that had no effect.

**Comment by joopringelberg** [comment]
Sorry for the rapid flipping state, but the problem returned this morning. Apparently the reinstalling effected something that has fallen over again. 
I noticed that in another (much smaller, test-) project, fast rebuild actually works.

**Comment by nwolverson** [comment]
Bower install in itself is unlikely to fix such an issue, unless you had some wrong versions (and did several other things).

If something is weird, remove `output/*`, run a full build, restart psc-ide (there's a menu option). Open the developer console and check for logging there

**Comment by joopringelberg** [comment]
Thanks a lot, that makes a difference. Before bower install I emptied the output directory and that must have removed the problem, until it was reintroduced. Very useful to know this!

**Comment by nwolverson** [comment]
The "stopped working" state should not happen unless you change [what should be] in `output` under the hood, like by doing a build outside of the editor, in which case generating the correct build output first and then reloading ide server in the editor should get back on track.

If you didn't do some external action as suggested, please do keep an eye on whether you can figure out what the trigger is, and check the console output so we can track it down.

**Comment by joopringelberg** [comment]
What I do quite regularly is build from the command line, so I have a better layout for the messages. So I'll work in the editor and if something really long is put on screen, I'll build from the command line. I must have done that hundreds of times but never had a problem until a couple of days ago.
I'll let you know when it happens again and try to figure out what triggers it.
