### ISSUE TITLE
Type info tooltip not displaying

### ISSUE THREAD

**Issue by AesaKamar** [nwolverson/atom-ide-purescript#193]
Freshly installed. 

I don't see the type info tooltip for any of these variable bindings. 

No tooltip displays when overing over variable `x`, nor `hello`, nor `there`

![image](https://user-images.githubusercontent.com/4334491/42596332-499d7ffc-8523-11e8-878c-b1a8fd13c061.png)

**Comment by nwolverson** [comment]
This is not supported for `hello`/`there` due to limitations of `purs ide`, tooltips only appear for top-level identifiers. And in that case (`x`) you should already have successfully built (either within atom with the build command or hit restart purs ide after).

**Comment by AesaKamar** [comment]
Would this not be possible to query for using the `Type` command?

https://github.com/purescript/purescript/blob/master/psc-ide/PROTOCOL.md

**Comment by nwolverson** [comment]
That is exactly what is used (via [purescript-language-server](https://github.com/nwolverson/purescript-language-server))

**Comment by kritzcreek** [comment]
Fwiw the way you get at types for local definitions is through typed holes,

For your example:

```purescript
x :: Array Int
x = do
  hello <- [1]
  there <- [1]
  let _ = ?x
  pure there
```

makes the compiler respond with:

```
 Hole 'x' has the inferred type

    t0

  You could substitute the hole with one of these values:
  blablabla

  in the following context:

    hello :: Int
    there :: Int


in value declaration x

where t0 is an unknown type
```

And if your context grows too large you apply the hole to the exact value you care about.
