### ISSUE TITLE
Go to definition doesn't seem to work

### ISSUE THREAD

**Issue by mnn** [nwolverson/atom-ide-purescript#198]
I think I have it setup properly - I can see errors being underlined, I can see types, but I cannot navigate to definition. Not to other files, not to definition in a same file. I tried original hotkey, custom hotkey and command from menu.

I would appreciate any advice how to make it work.

Atom: 1.13.0
ide-purescript: 0.19.1
pulp: 12.3.0
purs: 0.12.0

**Comment by mnn** [comment]
Strange, day later it started working even though I did not change tools, project setup or editor settings. 🤨 Not sure what changed.

**Comment by nwolverson** [comment]
Go to definition is powered by `purs ide` which uses a set of source filename globs on startup - one possibility is if the set of globs changed after starting the server (e.g. adding dependencies which aren't picked up)
