### ISSUE TITLE
Parsing the imports breaks with formatting

### ISSUE THREAD

**Issue by kritzcreek** [nwolverson/atom-ide-purescript#20]
Currently atom-ide-purescript only parses inputs of this format:

``` haskell
import Prelude
import Data.Array
import Data.Foldable
import qualified Data.Map as M
import Data.Tuple (Tuple(..), snd)
import Openspace.Types
```

This only loads the Data.Map import

``` haskell
import           Prelude
import           Data.Array
import           Data.Foldable
import qualified Data.Map as M
import           Data.Tuple (Tuple(..), snd)
import           Openspace.Types
```

**Comment by nwolverson** [comment]
Should work against this branch: https://github.com/nwolverson/atom-ide-purescript/tree/qualified-completion (though maybe needs to be rebased with `psc-ide` output changes)

Quite happy with the qualified completion so far (both for qualified imports and arbitrary fully qualified modules that may not be imported)

**Comment by kritzcreek** [comment]
Regexes are black magic to me :D  
But I'm hyped to try out the qualified completions!

Right now I'm managing my atom-ide-purescript with the in editor plugin manager.
How shouild I manage it so that I can checkout your branches and try them out?

**Comment by nwolverson** [comment]
They're bit approximate regexes just now but should be able to match the ps parser precisely for this. I guess if you're actually allowed to split imports multiline I won't support that.

If you uninstall in the atom package manager, checkout from the repo, and in the package source dir run `apm install` then `apm link`

**Comment by nwolverson** [comment]
Can you check this against latest published package?

**Comment by kritzcreek** [comment]
This works fine now :+1:
