### ISSUE TITLE
commented code deleted during import change

### ISSUE THREAD

**Issue by safareli** [nwolverson/atom-ide-purescript#200]
If you have:

``` purs
module Foo where

import Prelude
-- some comment here
import Data.Array as Array
```

Then if you type `foo = String.split` and select the import by pressing enter I get this:

``` purs
module Foo where

import Prelude
import Data.Array as Array
import Data.String as String

foo = String.split
```

note the comment is removed

**Comment by kritzcreek** [comment]
https://github.com/purescript/purescript/blob/master/psc-ide/DESIGN.org#we-pretty-print-the-entire-import-section-on-every-import-command-instead-of-patching-the-existing-section

It's purs ide's fault and it's part of the design.

**Comment by safareli** [comment]
makes sense, you can't really maintain comments if imports are being reordered.
