### ISSUE TITLE
Error running build - Spago + language release problem?

### ISSUE THREAD

**Issue by JordanMartinez** [nwolverson/atom-ide-purescript#201]
## Problem

I started getting this issue after I switched to using Spago and a newer PS release came out. I later switched to a new computer and still get the same problem.

After opening a project, I run the `build` command and get the following error message:
```
Error running build: Nothing : (Just "/home/user/path/project/")
PureScript (purescript-language-server) /home/user/path/project/
```
I cannot figure out where that error message appears in the code.

## Workarounds

- See [my later comment](https://github.com/nwolverson/atom-ide-purescript/issues/201#issuecomment-484763688)
- See [my concluding comment](https://github.com/nwolverson/atom-ide-purescript/issues/201#issuecomment-487293760)

## Environment info
```
# Main programs
node: v10.15.3
npm: 6.9.0
purs: 0.12.5
spago: 0.7.5.0
dhall-to-json: 1.2.7

# Atom specifically
Atom    : 1.36.1
Electron: 2.0.18
Chrome  : 61.0.3163.100
Node    : 8.9.3

# Atom packages
atom-ide-ui: 0.13.0
ide-purescript: 0.25.0
language-purescript: 0.9.0

# build command used
spago build -- --json-errors

# OS
Linux Mint 19.1
```

(Other unrelated content below)

<hr>

For more context, I sometimes have my learning repo opened at its root directory:
```
root
- spago project
-- src
-- test
- spago project
- etc...
```
I open an individual spago project when I need the code completion and whatnot. I'm not sure whether this affects things or not.

**Comment by JordanMartinez** [comment]
Update: not sure why this seems to work, but if I edit a `.purs` file, save it, and then build the project,
things work fine.

**Comment by nwolverson** [comment]
If anything needs to change on upgrading compiler version, I'd thought it was `rm -rf output/*`

I'd expect opening a project at the root directory to not give completion etc, but not particularly screw things up - actually what you can do is add the spago project as a workspace folder (and move it above the root folder) to have everything open at once with IDE support, I use things like this regularly.

If you are seeing inconsistent behaviour, are there multiple versions of `purs` available perhaps, eg one from `npm` somewhere? If you are ending up using different versions from the plugin, from command line, from build etc things may get weird

**Comment by JordanMartinez** [comment]
On this computer, I only have `0.12.4` installed.

I just nuked the `output` folder to ensure that wasn't causing an issue. However, the issue still arises.

I also opened a project where the project structure is what one would expect in a Spago-based project.

I've found that this workaround is always reliable:
- open atom via `atom -f`
- build the project (which fails)
- make a small change (e.g. add a space character)
- save the file
- build the project (it now builds)

Perhaps there's a caching issue somewhere?

Note: if I make a file change, save it, and then build (i.e. no failing build attempted before this) then the build will fail. I must first attempt to build the project before the 'save modified file and then build' approach works.

**Comment by bblfish** [comment]
I had a similar problem. I followed (some of) the instructions on https://qiita.com/kimagure/items/570e6f2bbce5b4724564 and that helped. I was missing psc-package. Perhaps that is the same problem?

**Comment by JordanMartinez** [comment]
Thanks for the tip @bblfish. I just tried that, but it did not change anything.

**Comment by JordanMartinez** [comment]
I have another update on this.

First, using my workarounds makes the project build. This means this project is working as expected in at least some situations.

Second, I learned that when I start Atom via the command `atom`, then this issue arises. However, if I pass it some other flags (e.g. `atom -f` `atom -l` `atom --enable-electron-logging`), then the project builds fine.

So, I think the issue at hand here is something related to Atom, not this project. I'll close this issue for now and edit my original post to link to this comment.

**Comment by AndrewBrownK** [comment]
I just picked up development after about a month hiatus and ran into this issue. For me this is what solved it:
- Upgraded node from 9.2.0 to 10.15.3 (using nvm)
- Updated npm to 6.9.0 (using nvm)
- Updated purescript to 0.12.5 (using npm)
- Updated pulp to 12.3.1 (using npm)
- In the settings of ide-purescript in atom, change the build command from my custom one to the default one. I tried this because of [this](https://github.com/nwolverson/atom-ide-purescript/commit/4a69e4dbf4e2d976a1cbffcb4b54c02a52517f02#diff-04c6e90faac2675aa89e2176d2eec7d8R25) two year old recommendation, even though my build was working normally merely two months ago. I must have updated atom or a package requiring a later version of psc at some point during the last month without realizing the consequences.

**Comment by JordanMartinez** [comment]
Another factor that might be relevant here... I believe I installed Node via `nvm` on the new computer rather than manually downloading and installing it on my previous one. @AndrewBrownK Did you install node through that manner as well?

**Comment by JordanMartinez** [comment]
I know this issue is closed, but I recently ran `sudo apt-get purge atom`, reinstalled it, and this problem went away. So, perhaps I installed an older version of atom at one time, and created a desktop entry that worked for that version of atom. Then, perhaps they released a newer version of atom and when I upgraded to that version, the desktop entry did not also get updated...?
