### ISSUE TITLE
Linter support

### ISSUE THREAD

**Issue by born2defy** [nwolverson/atom-ide-purescript#22]
I know that Linter support is experimental in this release, but should it be working in any form?  On every save command I receive the pop-up alerts letting me know the linter has been run, but it fails to detect any errors.  I am able to get auto-completion and tool tips working, but the build command is also failing with the following error: 
Executing with sh: pulp  build
Unable to execute with sh: pulp

Building via the terminal (powershell) works fine.  This is on Windows 7.

**Comment by nwolverson** [comment]
It "works for me" though with not so good errors since the error message format changed recently. But I'm using a Mac.

Is `pulp` installed in your path and Atom launched in such a way that it inherits your PATH? The atom-ide-purescript package has a configuration option for the build program, so you could also try specifying an absolute path.

**Comment by born2defy** [comment]
`pulp` is on my path and I believe atom is inheriting it although I'm sure how to be certain of that.  I have no problem using `cabal` thru atom for instance. I checked in the configuration options but the option states to enter a custom build command and not a path, so I'm not sure where I would enter the absolute path.  On the linting side, when I save a `.purs` file, the linter message runs and is immediately followed up by a success message.  I do not believe it is actually compiling anything though as no errors are ever detected.  Let me know if there is any specific info you would like to try and pinpoint the issue.  Otherwise, having a sensible auto-complete is already a huge leap forward, but the linting functionality would really be great to be able to utilize.

**Comment by nwolverson** [comment]
(Linting may be over-selling what is simply compile-on-save, it's just the package name)

I think `pulp` is being called correctly but errors are not being picked up. Some possible issues (which we should be able to do something about)
- Atom project isn't open in your project root - open the folder which contains a `src` directory at the next level, i.e. the directory you would run `pulp` from on the command line
- Errors aren't being parsed, to diagnose this would be good to get versions of `psc` and `atom-ide-purescript` installed

(Have a look at https://github.com/atom-community/linter/issues/150 regarding the path; if you open up atom developer tools and evaluate `process.env.PATH` and see if that looks right, if not the "custom build command" is really exactly something that will be exec'd, so an absolute path might help. But you should see a big red error in this case.)

**Comment by born2defy** [comment]
Adding a specific build command with an absolute path allowed me to get some linting results.  Didn't detect any issues in type errors (for instance a number posing as a string), but did detect parsing errors like incomplete lines.  Is that as expected?

**Comment by nwolverson** [comment]
Expectation: With latest `psc` installed (0.7.4.1) every error or warning reported by running `psc` / `pulp` build will be reported. I know the format changed a bit at some point and I need to polish the matching, but I do see that category of error:

![image](https://cloud.githubusercontent.com/assets/2770891/9897748/ede318c6-5c43-11e5-9222-9a1031fcecff.png)

as well as parse error:

![image](https://cloud.githubusercontent.com/assets/2770891/9897760/0f690b2c-5c44-11e5-9b5b-eef36ef9ecfe.png)

If you can post the error message you get when building on the command line that doesn't show up in the plugin I can ensure that it gets detected.

**Comment by born2defy** [comment]
I was able to replicate the same results you are getting after restarting the psc-ide server.  Really nice work - especially for an initial release.
