### ISSUE TITLE
Completion for imports

### ISSUE THREAD

**Issue by nwolverson** [nwolverson/atom-ide-purescript#24]
Currently modules will be completed (somewhat) but only from the modules currently present in the file. Is even everything loaded enough? Probably you might want to complete anything present in the project (which might not be imported in any file you visited this session), or more generally something that might need to be installed.

**Comment by kritzcreek** [comment]
There is a more general problem here. Bower flattens all the dependency. So there is no way to differentiate a direct dependency of a project from a transient dependency. The only "solution" I currently see is parsing the bower.json file and then looking up the modules that belong to the dependencies.

**Comment by nwolverson** [comment]
I don't even know what I want in import completion, I imagine there might be different opinions (e.g. on transitive dependencies). More or less magic. Input welcome.

**Comment by nwolverson** [comment]
Currently there's an "add import" command, should take the same suggestion of modules to autocomplete import declarations. Right now it's useless.

**Comment by nwolverson** [comment]
Completion for import statements from installed packages now in the PureScript version
