### ISSUE TITLE
Failed to spawn command `pulp`

### ISSUE THREAD

**Issue by kristianmandrup** [nwolverson/atom-ide-purescript#31]
Failed to spawn command `pulp`. Make sure `pulp` is installed and on your `PATH`

``` sh
$ which pulp
/Users/kristianmandrup/npm/bin/pulp
```

What am I missing in my configuration?

Might be related to this issue? https://github.com/atom-community/linter/issues/150

ie.

``` sh
This still occurs when launching from Terminal or Gui on Mac OS (Yosemite)

Uncaught BufferedProcessError: Failed to spawn command pep8. Make sure pep8 is installed and on your PATH 
Uncaught BufferedProcessError: Failed to spawn command pylint. Make sure pylint is installed and on your PATH
```

https://libraries.io/atom/ide-purescript

_This package relies on having psc-ide installed. Version 0.3.0.0 is supported (release). This runs a server process, psc-ide-server, to provide type information, completions, etc. This package will automatically start psc-ide-server in your project directory (port is configurable) and kill it when closing, if for some reason you want a longer running server process you should be able to start that before starting atom.

You must install the atom package language-purescript! You should optionally install atom packages Linter or Build if you want build support, see below._

I can confirm that I have installed `language-purescript` plugin as well. I'm not sure which optional `Linter` or `Build` you mean? I guess you mean the base `Linter` (with Cow powers)?
https://github.com/atom-community/linter

I have `psc-ide` and `psc-ide-server` installed and on my path. `pulp` was installed via npm and I can see it in `~/npm/bin`

in my `~/.bash_profile

```
PATH=~/psc-ide:$PATH
PATH=~/purescript:$PATH
PATH=~/npm/bin:$PATH
```

I can run `pulp` just fine from the command line.

``` sh
$ psc-ide-server
psc-ide-server: bind: resource busy (Address already in use)

$ psc-ide -h
Usage: psc-ide [-p|--port ARG]
```

I can see `psc-ide-server` running in my Activity Monitor (Mac OSX)

**Comment by kristianmandrup** [comment]
Solved it by setting path in init file `~/.atom/init.coffee`

`process.env.PATH = ["~/npm/bin", process.env.PATH].join(":")`

**Comment by nwolverson** [comment]
General OSX/atom issue, dotfiles don't influence the `PATH` when not run from a command shell. There is a workaround package but not ideal, see if atom will fix sometime...

Optional linter or build - this should be linked already (at least it is in the `README`, maybe should switch to the atom package) https://github.com/atom-community/linter is correct
