### ISSUE TITLE
Error parsing broken with 0.7.5

### ISSUE THREAD

**Issue by nwolverson** [nwolverson/atom-ide-purescript#35]
PureScript 0.7.5 error format has changed.

**Comment by born2defy** [comment]
I was just going to add this.  Doesn't seem like any of the linting works anymore.

**Comment by nwolverson** [comment]
Never fear, an updated regex is nearly here.

**Comment by nwolverson** [comment]
This should now work (either with linter display on save, or build plugin). The errors are now pretty much impossible to read, I think a move to a new build process rather than using these plugins will help.

**Comment by born2defy** [comment]
Hey - for whatever reason I cannot get the linter to work.  Do you need a specific version of atom-linter that this is designed to work with?  I can build and get errors, but when saving I see the "linter compiling purescript" message, but nothing seems to be happening.

**Comment by kritzcreek** [comment]
This happened to me when atom couldn't find pulp on the path. Did you try starting atom from the command line?

**Comment by nwolverson** [comment]
psc version? I tested with 0.7.5.3

You say nothing happens, I guess this means the 2nd message of "compiled purescript" never appears? Or that appears but no errors are found? The error parsing may be flaky and depend on exact compiler version as it keeps changing :(

Can you check developer tools in atom, anything appearing in the console?

Regarding not on the path, I think that would show an error message. Just updated my installed linter plugin version and I notice something is erring, will fix that just now.

**Comment by born2defy** [comment]
I am using 0.7.5.3 also.  I have experimented with opening atom directly and also via the command line - same result.  The "compiled purescript" does appear, but almost instantly, and no errors are ever returned via the linter - although if I use the build command in atom the errors get reported in the build results.  In the console here is what I see when I save:

psc-ide.coffee:30
psc-ide {"command":"list","params": {"type":"import","file":"N:\Haskell\Purescript\validator\src\DOM\GetBody.purs"}} --> {"resultType":"success","result":[{"module":"Prelude","importType":"implicit"},{"module":"Data.Maybe","importType":"implicit"},{"module":"Data.Maybe.Unsafe","importType":"implicit"},{"module":"Data.Nullable","importType":"explicit","identifiers":["toMaybe"]},{"module":"Control.Monad.Eff","importType":"implicit"},{"module":"DOM","qualifier":"DOM","importType":"implicit"},{"module":"DOM.HTML","qualifier":"DOM","importType":"implicit"},{"module":"DOM.HTML.Document","qualifier":"DOM","importType":"implicit"},{"module":"DOM.HTML.Types","qualifier":"DOM","importType":"implicit"},{"module":"DOM.HTML.Window","qualifier":"DOM","importType":"implicit"},{"module":"DOM.Node.Types","qualifier":"DOM","importType":"implicit"}]}

psc-ide.coffee:30  exited with code 0

editors.coffee:60 
Active modules: {"main":"DOM.GetBody","modules":["Prelude","Data.Maybe","Data.Maybe.Unsafe","Data.Nullable","Control.Monad.Eff"],"qmodules":[{"module":"DOM","qualifier":"DOM","importType":"implicit"},{"module":"DOM.HTML","qualifier":"DOM","importType":"implicit"},{"module":"DOM.HTML.Document","qualifier":"DOM","importType":"implicit"},{"module":"DOM.HTML.Types","qualifier":"DOM","importType":"implicit"},{"module":"DOM.HTML.Window","qualifier":"DOM","importType":"implicit"},{"module":"DOM.Node.Types","qualifier":"DOM","importType":"implicit"}]}

**Comment by born2defy** [comment]
Could this line be meaningful: psc-ide.coffee:30 exited with code 0?

**Comment by born2defy** [comment]
By the way, just wanted to also say thank you to both @nwolverson and @kRITZCREEK for the hard work on creating a really nice developer experience for purescript on Atom.  These minor issues aside, the auto-complete and errors-on-save are incredible time savers.

**Comment by nwolverson** [comment]
Closing this again, the actual issue listed is fixed long time ago. @born2defy if you still have an issue with linter not showing errors, please raise a new issue specific to that. I am re-writing this for 0.8 anyway

**Comment by born2defy** [comment]
Ok, I will wait for the new version. I have been using the build tool to check for errors since raising this issue as I just can't get the linter to work.
- Adam
