### ISSUE TITLE
vscode version?

### ISSUE THREAD

**Issue by stkb** [nwolverson/atom-ide-purescript#37]
(Accidentally initially submitted this issue with no text)

Hi I noticed that you'd already created the "PureScript Language Support" package for Visual Studio Code and was wondering if you were planning on also making a similar extension as atom-ide-purescript for vscode.

If not, then I was thinking of making a start on it.

**Comment by nwolverson** [comment]
Yes I think it's a good idea, it's probably also a good time to consider if something can be extracted/shared. And writing this in CoffeeScript was probably a bad idea, that may be the standard in the Atom world but not for vscode, I wonder if biting the bullet and doing the plugins in PureScript makes sense.

**Comment by nwolverson** [comment]
Started something https://github.com/nwolverson/vscode-ide-purescript - should quickly get some basics ported over. Pretty nice API there.
