### ISSUE TITLE
Conflict with another package

### ISSUE THREAD

**Issue by makar-al** [nwolverson/atom-ide-purescript#42]
There is a conflict with package [latex-completions](https://atom.io/packages/latex-completions) (it works only when `atom-ide-purescript` is disabled). Since purescript now supports unicode, it would be nice to have some kind of autocompletion for it. Ideally as a part of `atom-ide-purescript`.

**Comment by nwolverson** [comment]
A question of priority & exclusion of completion provider. This should be fixed as part of the linked PR - whenever that package is next released.
