### ISSUE TITLE
Uncaught TypeError: Cannot read property 'resultType' of undefined

### ISSUE THREAD

**Issue by passy** [nwolverson/atom-ide-purescript#44]
Happens directly after opening a Purescript project. I hope this is not just me having an outdated version of something, I've tried my best to update everything that could be relevant.

**psc Version:** 0.8.0.0
**pulp Version:** 8.0.0
**psc-ide Version:** 0.6.0
**Atom Version**: 1.4.2
**System**: Mac OS X 10.11.3
**Thrown From**: [ide-purescript](https://github.com/nwolverson/atom-ide-purescript) package, v0.8.1
### Stack Trace

Uncaught TypeError: Cannot read property 'resultType' of undefined

```
At /Users/phartig/.atom/packages/ide-purescript/lib/psc-ide.coffee:31

TypeError: Cannot read property 'resultType' of undefined
    at exit (/Users/phartig/.atom/packages/ide-purescript/lib/psc-ide.coffee:31:22)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:220:18
    at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:98:18)
    at emitOne (events.js:82:20)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```
### Config

``` json
{
  "core": {},
  "ide-purescript": {}
}
```
### Installed Packages

``` coffee
# User
atom-typescript, v8.2.0
clipboard-plus, v0.5.1
haskell-pointfree, v0.1.3
hex, v0.6.2
hover-tooltips, v0.3.0
hover-tooltips-hdevtools, v0.10.0
ide-flow, v0.8.0
ide-haskell-cabal, v1.0.0
ide-purescript, v0.8.1
language-elm, v1.3.2
language-gradle, v0.0.3
language-groovy, v0.5.0
language-haskell, v1.5.2
language-purescript, v0.6.1
linter, v1.11.3
linter-elm-make, v0.4.0
linter-hlint, v0.4.2
linter-javac, v1.5.0
relative-numbers, v0.4.1
vim-mode, v0.64.0
vim-mode-clipboard-plus, v0.2.0
vim-mode-visual-block, v0.2.15
vim-surround, v0.8.1

# Dev
No dev packages
```

**Comment by kritzcreek** [comment]
Could you start `psc-ide-server --debug` in your projects root directory, then open the project in atom and see what output you get?

**Comment by nwolverson** [comment]
Versions look good. As well as what @kRITZCREEK asks, be good to open the developer console in atom and see if there's anything there, there should hopefully be a line with `-->` or some info. Failing that I also just pushed a new patch version that might have slightly better error output in this case.

**Comment by passy** [comment]
Sorry, appears to have been a false positive. It's all good now. My suspicion is that there was an outdated process still running on the same port.

Sorry for the noise!

**Comment by nwolverson** [comment]
No problem, glad you got it working.
