### ISSUE TITLE
lintOnSave: resolve is undefined when !buildOnSave

### ISSUE THREAD

**Issue by sloosch** [nwolverson/atom-ide-purescript#46]
Hi there,

`resolve` at https://github.com/nwolverson/atom-ide-purescript/blob/master/lib/linter-purescript.coffee#L68 is undefined.

should be

```
return Promise.resolve([])
```

**Comment by nwolverson** [comment]
Fixed f268f46285667879b4fef95bfb1608e5f3566ac7

Clearly I have it turned on, and brain turned off when I wrote that...

**Comment by nwolverson** [comment]
And thanks!
