### ISSUE TITLE
Renamed psc-ide to psc-ide-client

### ISSUE THREAD

**Issue by kritzcreek** [nwolverson/atom-ide-purescript#51]
In order to be more consistent I renamed the `psc-ide` exectuable into `psc-ide-client`. This will take effect with the purescript-0.8.1 release.

**Comment by nwolverson** [comment]
Thanks for the info. As of the current release the plugin is connecting directly to the server but opened https://github.com/nwolverson/vscode-ide-purescript/issues/2 as code plugin is not (and it's not configurable I think...)

**Comment by kritzcreek** [comment]
ahh great! That's even better!
