### ISSUE TITLE
Build notifications are obtrusive

### ISSUE THREAD

**Issue by sloosch** [nwolverson/atom-ide-purescript#52]
Remove or provide an option to disable the messages "Building PureScript" and "PureScript build succeeded" when "build on save" is enabled.
https://github.com/nwolverson/atom-ide-purescript/blob/master/src/IdePurescript/Atom/LinterBuild.purs#L83
https://github.com/nwolverson/atom-ide-purescript/blob/master/src/IdePurescript/Atom/LinterBuild.purs#L89

These messages are somehow distracting me every time.

**Comment by nwolverson** [comment]
I guess those are there because the compiler is so slow for building on save. It might be nice to indicate this quietly in the status bar.
