### ISSUE TITLE
Suggested build command for use with tests

### ISSUE THREAD

**Issue by paulyoung** [nwolverson/atom-ide-purescript#53]
I've been using `pulp build --src-path test --include src` as my build command since files in the test directory were otherwise not providing error or linter information.

**Comment by nwolverson** [comment]
What's your workflow, how do you think this should manifest in the atom package? ie I assume you want to see if your changes have stopped your tests building (on save?), thinking also things have to work for projects with no test folder. Or is this a documentation suggestion?

**Comment by paulyoung** [comment]
I have a project with `src/` and `test/` directories and noticed that I wasn't seeing warnings about problems in my test files.

It _was_ a documentation suggestion since not all projects have a `test/` directory and everything stops working when using this command in that case.

Since there's no ability to have per-project settings (that I know of) it would be great to have it "just work" either way.

I tried `if [ -d ./test ]; then pulp build --src-path test --include src; else pulp build; fi` but that causes an error in Atom.

**Comment by nwolverson** [comment]
I'll think to add a configuration tips section at least. You could write yourself a script that does that and invoke that?

**Comment by paulyoung** [comment]
Yeah, good idea.

**Comment by paulyoung** [comment]
Just wanted to add that it's now necessary to also pass `--json-errors`.

**Comment by paulyoung** [comment]
Also, @hdgarrood pointed out that `pulp build --include test` would work, so now I'm using `pulp build --include test --json-errors`.

**Comment by paulyoung** [comment]
Another update – after some discussion in https://github.com/bodil/pulp/issues/192, I have `npm run build` set up like so:

``` json
{
  "scripts": {
    "build": "pulp build --include test"
  }
}
```

and I've set my build command for  `atom-ide-purescript` to:

```
npm run build -- --json-errors
```

This way:
- each project can set `npm run build` to include zero or more relevant directories.
- errors are only output in JSON format when invoked from Atom.

**Comment by nwolverson** [comment]
I've updated the README to include some more detailed notes on build configuration and the above tip, does this make sense?

**Comment by hdgarrood** [comment]
Looks good but I think your example of using psc directly will miss FFI files.

**Comment by nwolverson** [comment]
Did I dream that those are automagially picked up now? Is it that you don't need to explicitly say `--ffi` but you still need to pass in the glob?

**Comment by hdgarrood** [comment]
Yes, I think that's it.

**Comment by nwolverson** [comment]
Updated that, apparently `.{purs,js}` works nicely. Thanks for the spot.

**Comment by hdgarrood** [comment]
I think that might be your shell, unfortunately. The Haskell package `Glob` doesn't recognise that kind of pattern:

```
$ psc 'src/**/*.{purs,js}' 'bower_components/purescript-*/src/**/*.{purs,js}'
psc: No files found using pattern: src/**/*.{purs,js}
psc: No files found using pattern: bower_components/purescript-*/src/**/*.{purs,js}
psc: No input files.
```

**Comment by hdgarrood** [comment]
We could use `src/**/*` after https://github.com/purescript/purescript/issues/1937 is fixed, though.

**Comment by nwolverson** [comment]
@hdgarrood Dammit, I assumed it wasn't my shell because I tested on windows, apparently that was under bash, I'll update to the simple thing for now. I guess `*.*` should also work though.

**Comment by paulyoung** [comment]
Thanks!
