### ISSUE TITLE
Default build command on Windows is problematic

### ISSUE THREAD

**Issue by TerrorJack** [nwolverson/atom-ide-purescript#54]
Somehow, the `pulp` in the default build command should be changed to `pulp.cmd` on Windows, as mentioned in #33 . However, I had to manually change the default build command, and after checking https://github.com/nwolverson/atom-ide-purescript/blob/d30ae16f3dd3dc421c666ccade97108b186f308b/src/IdePurescript/Atom/Config.purs#L6 I am surprised to see the switching has been commented out! Is there a good reason for that?

Also, using the default build command, build is not triggered at all, and there simply is no error message for failing to build, simply no build errors. Is there any way to fix this?

**Comment by nwolverson** [comment]
Sorry, this is commented because it never got ported to the PureScript version, I'll look to add that back in. 

I'll check on the errors too.

**Comment by nwolverson** [comment]
Should now be fixed (published new version). Errors should also now show up.
