### ISSUE TITLE
linter does not work

### ISSUE THREAD

**Issue by eskimor** [nwolverson/atom-ide-purescript#55]
If I save a file, all I get is (after "Building PureScript"):

![atom-error](https://cloud.githubusercontent.com/assets/1527017/13872762/e83cfa1a-ecec-11e5-8f73-a916e5403c6e.png)

I am running nixos unstable, atom version: 1.5.4, psc : 0.8.2

I changed the psc-ide command to psc-ide-client as psc-ide does not exist. I assume the name has changed?

Maybe you have an immediate idea what went wrong?

Btw, thanks for an awesome atom-ide-purescript!

**Comment by nwolverson** [comment]
Hi,

Firstly regarding psc-ide, maybe the config is unclear, the client is not used (though the name of that did change), and psc-ide-server must be configured as psc-ide-server executable location (config option `pscIdeServerExe`). 

But the build command doesn't use psc-ide anyway. Not sure if you have a non-default build command, but it must output JSON errors:

```
Should output json errors (old format will still be supported for now)
```

This text in the config is actually incorrect, I dropped non-JSON error support when translating to PureScript. Build command should be something like the default, eg:

```
pulp build --json-errors
```

**Comment by eskimor** [comment]
Awesome! When I set the build command from default to

```
pulp build --json-errors
```

it works! So neat! :-) Thanks a lot! Awesome! Awesome. So neat! Thank you!
