### ISSUE TITLE
Update imports automatically 

### ISSUE THREAD

**Issue by nwolverson** [nwolverson/atom-ide-purescript#57]
On autocompletion could insert an explicit import clause

**Comment by kritzcreek** [comment]
I'd be happy to implement some support for this inside psc-ide. The main question I have is whether the command should take a filepath or the editor should put the import section into the request.

**Comment by nwolverson** [comment]
Yeah that would be the best idea, at least I worry about correctly parsing and pretty-printing an import statement. However I'm not clear how it should work with modified files, which won't compile - ideally we'd use the proper PS parser to handle imports but not require the rest of the file to be parseable.

Take your call on where that goes, you probably want to be consistent with other things - I guess with other tooling it's common to write the currently edited file out to a tempfile in this sort of situation?

**Comment by nwolverson** [comment]
This is now happening. (Some tweaks to be had no doubt)

**Comment by kritzcreek** [comment]
:tada:
