### ISSUE TITLE
Relax autocomplete suggestion filtering

### ISSUE THREAD

**Issue by nwolverson** [nwolverson/atom-ide-purescript#59]
I like that suggestions that are currently imported are shown, exact matches. But 
- Consider if a different matcher is better (I know I was looking for camelHumps, not sure if the flex matcher is the right choice)
- Some way to get completions outside of the currently imported modules. I don't know if this is a separate command (like triggering autocomplete a 2nd time) or if these can be in the same list but scored lower

**Comment by kritzcreek** [comment]
https://github.com/purescript/purescript/pull/1965 should be relevant for your first point.

With these changes applied I turned the flex matching back on in emacs.

**Comment by nwolverson** [comment]
Point 2 is already handled in autocomplete. I think point 1 is not a good idea for autocomplete given the range of suggestions in other modules

Implemented flex for search only.
