### ISSUE TITLE
Add language-purescript to package-deps?

### ISSUE THREAD

**Issue by damncabbage** [nwolverson/atom-ide-purescript#60]
#50 added dependency installation, and it's currently being used to bring in `linter`.

As the README directs users to install https://atom.io/packages/language-purescript manually, would it be possible to add the dependency to package.json instead?

**Comment by nwolverson** [comment]
I guess, but it's not _entirely_ that simple. Right now this package only loads on opening a file in the PureScript language, and that is defined by language-purescript. So there needs to be some load trigger (I don't want to make it always-on, if nothing else it does something on startup).

I can make the provided commands trigger the package load, maybe also add them to a menu for discoverability.

**Comment by damncabbage** [comment]
Ah, pardon me. I'm a complete newbie when it comes to Atom, and though I'm aware package dependencies is an add-on the community came up with, I thought it'd be possible to add a one-time cost to install language-purescript if it wasn't present. Please pardon me if I'm barking up the wrong tree, and thanks for the reply.

**Comment by nwolverson** [comment]
No I think it's a valid point, just a bit awkward. Can do something at least.

**Comment by damncabbage** [comment]
:heart_eyes_cat:

(Thanks.)
