### ISSUE TITLE
Add a 'restart psc-ide-server' command

### ISSUE THREAD

**Issue by nwolverson** [nwolverson/atom-ide-purescript#61]
I reload the plugin by hand but there should probably be something in a menu to restart this

**Comment by garyb** [comment]
:+1: for this. How do you reload it by hand?

edit: nevermind, I see!

**Comment by nwolverson** [comment]
Reload the atom window, command alt L on mac, Control alt R on windows  - or from the command palette.

**Comment by nwolverson** [comment]
This is now in. Though it won't kill it if it doesn't exit gracefully, and not sure if things go wrong if you reconfigure the port in the interim.

**Comment by garyb** [comment]
Thanks for adding this :smile:

**Comment by nwolverson** [comment]
No problem, turns out if you have 'start' and 'stop' then 'restart' is fairly easy to come by...
