### ISSUE TITLE
Make psc-ide-server from npm work out of the box on windows

### ISSUE THREAD

**Issue by nwolverson** [nwolverson/atom-ide-purescript#63]
That old `.cmd` again. Not good enough to default to something different on windows as unlike pulp this could be either.

**Comment by kritzcreek** [comment]
Fixed by https://github.com/purescript/purescript/pull/2000?

**Comment by nwolverson** [comment]
Nope. This is the issue of the actual executable being called `psc-ide-server.cmd` if installed via npm, and `psc-ide-server` otherwise. `pulp` already handles this for the standard executables, and pulp is always via npm so we call that as `pulp.cmd`. Since this is also an issue for the vscode plugin I'll go with a common fallback approach probably https://github.com/bodil/pulp/blob/master/src/Pulp/Exec.purs#L139

**Comment by nwolverson** [comment]
Finally! No configuration required, if `psc-ide-server` is in your PATH it should be picked up, including both  `CMD` and `EXE` on windows (thanks to https://github.com/npm/node-which), hopefully nicer errors/warning if there is not exactly 1 found, and console log of the versions found...
