### ISSUE TITLE
Auto-complete not working

### ISSUE THREAD

**Issue by born2defy** [nwolverson/atom-ide-purescript#71]
This is in version 0.11.1.  The auto-complete suggestion list displays, but any action on the list items (tab, enter, mouse click) erases anything you have typed and inserts nothing.

**Comment by nwolverson** [comment]
Hmm. What is this completing? I think I may have broken this for module imports, but not identifiers.

Just pushed a new version, can you try now?

**Comment by born2defy** [comment]
Sorry - the imports were broken.  The new version fixes the import completion, but now none of the identifier completions are being triggered (no list of options pops up).

**Comment by nwolverson** [comment]
Hmm, can't reproduce that one. Have you tried the explicit autocomplete trigger (ctrl+space I think)?

**Comment by nwolverson** [comment]
Actually - I can reproduce on another machine, but possibly not the same issue; do you get tooltips still?

**Comment by born2defy** [comment]
Autocomplete trigger isn't working and neither are the tooltips.  This is on a Windows 7 Pro system.  Was working prior to the 0.11.x releases.  Rolling back to 0.10.0 fixes these issues for me.

**Comment by nwolverson** [comment]
Great, this at least we can fix. This seems to be related to the change to load modules in psc-ide differently (previously I loaded modules for the current file on file switch, now I was loading all available at startup). 2 options until I make this more robust:
-  Try rebuilding (unlikely this will work)
-  Nuke your output/ folder, rebuild, and restart the atom window (ctrl+alt+r on windows)
-  Run `psc-ide-server --debug` manually in your project folder, plus do the above, and see if modules in your project get loaded

**Comment by nwolverson** [comment]
Actually I think I inadvertently crated a dependency on purescript 0.8.4. Updated again, maybe you can try now? :)

**Comment by born2defy** [comment]
My friend, I think that did it.  Just took the new version for a test drive and auto complete was working for both imports and identifiers, as were tooltips (type info).  Seems like you solved it!

**Comment by born2defy** [comment]
By the way, can I say thank you again for the incredible support you have shown this community?
