### ISSUE TITLE
New Experimental Add Clause/Case Feature

### ISSUE THREAD

**Issue by born2defy** [nwolverson/atom-ide-purescript#74]
I would like to test these out for you, but I'm not sure exactly how to use them.  Can you provide a slightly more detailed explanation of how to use these features?

**Comment by nwolverson** [comment]
Yeah didn't get around to updating docs. Should probably make a gif...

Right now they are just commands, which you probably want to keybind. Write a type definition (toplevel), cursor over the identifier and hit add clause. Then on a function clause (at toplevel again), cursor over an argument (or select the argument pattern? I think) and hit case split.

**Comment by nwolverson** [comment]
![case-split](https://cloud.githubusercontent.com/assets/2770891/17080720/2c5391d8-5132-11e6-8bf3-0a7e0714da24.gif)

**Comment by nwolverson** [comment]
Updated in README.

Hopefully in future we can infer some of these types...

**Comment by jimmyhmiller** [comment]
Is there any fundamental limitation for case-split not inferring the type or just work that hasn't been done yet?

**Comment by nwolverson** [comment]
I think @kRITZCREEK said he started to prototype this at one point but didn't make it to psc-ide in the cleaned up version

**Comment by kritzcreek** [comment]
The "prototype" was a hack that tried to split type signatures with regexes. Really we'd need to use PureScript's type declaration parser but that would happen inside `psc-ide` and not Atom. The whole `addClause` `caseSplit` stuff is a little ad-hoc and I'd like to revisit it at some point.
