### ISSUE TITLE
Errors on launch/save

### ISSUE THREAD

**Issue by paulyoung** [nwolverson/atom-ide-purescript#75]
When I open a PureScript project in Atom, I see the following error:
`Could not start psc-ide-server process. Check the configured port number is valid. psc-ide-server error`

When I hit save, I see these:
`Error: connect ECONNREFUSED 127.0.0.1:4242 at Object.exports._errnoException (util.js:856:11) at exports._exceptionWithHostPort (util.js:879:20) at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1063:14)`

`Error running PureScript build command: Error: spawn npm ENOENT at exports._errnoException (util.js:856:11) at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32) at onErrorNT (internal/child_process.js:344:16) at doNTCallback2 (node.js:465:9) at process._tickCallback (node.js:379:17)`

I just got a new machine so had to do fresh installs of everything, but this was on a project that used to work on my old machine.

**Comment by nwolverson** [comment]
So looks like you don't have psc-ide-server available (though I might expect to see an ENOENT there too) - check https://github.com/purescript/purescript/wiki/psc-ide-Troubleshooting-&-FAQ. There's a known issue if you installed via npm on windows, need to change the configured psc-ide-sever in settings to `psc-ide-server.cmd`.

The build command - I'm a little confused at the `npm` reference, anyway if you have the default configuration maybe `pulp` is not being found in your path?

**Comment by paulyoung** [comment]
`which psc-ide-server` says `/Users/py/.nvm/versions/node/v5.10.1/bin/psc-ide-server`. I'm on OS X by the way.

My build command is set to `npm run build -- --json-errors` as discussed in https://github.com/nwolverson/atom-ide-purescript/issues/53#issuecomment-198621810

**Comment by nwolverson** [comment]
On OSX, make sure you are starting Atom from a terminal in order to get correct PATH available. You can check in the atom dev console `process.env.PATH` if this is correct

**Comment by paulyoung** [comment]
I just disabled [atom-fix-path](https://atom.io/packages/atom-fix-path) and everything works.

**Comment by paulyoung** [comment]
Thanks for the help!
