### ISSUE TITLE
Missing tooltips

### ISSUE THREAD

**Issue by doivosevic** [nwolverson/atom-ide-purescript#76]
I think theres a bug where the tooltip is not showing at all

0.13.0 ide-purescript
0.7.0 language purescript 
1.8.0-beta-2 atom

I get a notification that psc-ide-server is running when I restart Atom

**Comment by nwolverson** [comment]
Do you get autocompletion? As this is powered from psc-ide-server also.

(I'm not using 1.8 yet so it may well be broken)

**Comment by doivosevic** [comment]
Nope.
When I go to localhost:4242 it returns

```
{
result: "Error parsing Command.",
resultType: "error"
}
```

(if that helps)

**Comment by nwolverson** [comment]
I should add a troubleshooting section. See https://github.com/purescript/purescript/wiki/psc-ide-Troubleshooting-&-FAQ for psc-ide troubleshooting
- Your project must be built (externs in `output/` folder)
- If you build from outside the atom plugin, you might need to switch file/reload to get info
- Beware multiple versions of `psc-ide-server` in your path not matching the version you compiled with (eg due to npm and cabal/stack/etc installs)

**Comment by doivosevic** [comment]
- I do have externs in my output folder. I build with `pulp --watch browserify --to "dist/bundle.js" --main "Main"`
- I don't have autocomplete nor tooltip even after I restart atom
- I have 

```
       > where psc-ide-server
       C:\Program Files\nodejs\psc-ide-server
       C:\Program Files\nodejs\psc-ide-server.cmd
       C:\Users\Dito\AppData\Roaming\local\bin\psc-ide-server.exe
```

**Comment by nwolverson** [comment]
Looks like you have multiple compiler installations there, need to make sure the same one is being used in all cases, in particular the PATH used from within node scripts may be different. I'd recommend removing the previous version that you don't mean to use.

(BTW if you do build with such a watcher, you may need to switch back and forth between files when compilation finishes, and you'll miss getting errors in the editor)

**Comment by doivosevic** [comment]
I've tried changing the names of both files but neither makes tooltips appear.
I must admit that I'm a bit inexperienced with debugging atom extensions so I could help in debugging if you point me in some direction.
Could it be that some change in atom 1.8 made the hovering not trigger display of tooltips? I'd at least expect an exception if something were wrong.

**Comment by nwolverson** [comment]
Did you remove your old psc-ide-server executable? Did you follow @kRITZCREEK 's suggestion in troubleshooting per the link, to run with --debug flag? (If you do make such changes you should restart/reload atom after). Also: _if your newer version is the npm version, you will need to edit the configuration to use `psc-ide-server.cmd`_ (an explicit path could also help ensure you get what you want).

It looks like you have an old version which will prevent autocomplete & tooltips. Debugging the atom extension will not help in this case

**Comment by nwolverson** [comment]
Did you resolve this? I added some improved error messaging/logging to help diagnose this kind of issue, particularly on the versioning, as well as improvements regarding using the correct `psc-ide-server` executable.

**Comment by doivosevic** [comment]
It started working after some point (possibly after an update to something)
but I'm unsure why. Thanks

**Comment by nwolverson** [comment]
Great, happy days.
