### ISSUE TITLE
Tooltips font not easily readable

### ISSUE THREAD

**Issue by vstastny** [nwolverson/atom-ide-purescript#77]
In my opinion, the tooltips (e.g. function signatures) font is not easily readable. The issue is that white bold font on blue background is hard to read. I would suggest the tooltips be displayed in different way. For instance, VS Code tooltips are better.

**Comment by nwolverson** [comment]
They are indeed ugly. I think ide-haskell has better looking tooltips (editor styles and I think formatted).

**Comment by vstastny** [comment]
Thanks, but is there any plan to modify the tooltips or perhaps make it somehow configurable?

**Comment by nwolverson** [comment]
Yes, but it's not currently near the top of my todo list.

Right now we're using hover-tooltips but I was thinking about ripping out/off aforementioned ide-haskell stuff, possibly into a standalone package.

**Comment by vstastny** [comment]
Ok then. Just let me know if I should close the issue or leave it open for future reference. Thanks.

**Comment by nwolverson** [comment]
Please leave it open, it is an issue and not covered elsewhere. Thanks.

**Comment by garyb** [comment]
I'd prefer the option to choose hover tooltips if possible, if the ide-haskell style is introduced too. I ended up turning off tooltips in ide-haskell because they're really intrusive compared to what we have now, and often get in the way.

**Comment by nwolverson** [comment]
Is the issue the styling or just the sheer amount of information on them making them larger? We don't have to couple those 2 things.

My issue with them has been the fact they seem to take several seconds to appear for me, which wouldn't be an issue for us.

(Other than readability, an issue with the current tooltips is they can actually span my entire screen and still not get to the interesting bit of the type... But that's really due to erasure of type aliases)

**Comment by garyb** [comment]
> Other than readability, an issue with the current tooltips is they can actually span my entire screen and still not get to the interesting bit of the type

Yeah, that's very true.

The size of the ide-haskell ones is part of the problem, but also they often seem to be right in the way of where I want to click, and it's not obvious how to get rid of them. I suppose if we could introduce a small x-to-dismiss icon in the corner or something it would probably help a great deal with that.

**Comment by nwolverson** [comment]
@vstastny in any case right now, you can likely already style the tooltips with your atom user styles. Check the styles here:

https://github.com/ranjitjhala/hover-tooltips/blob/master/styles/hover-tooltop.less

eg something like:

```
.hover-identifier-tooltip .tooltip-inner {
  background: hotpink;
  border: 1px solid white;
  border-radius: 3px;
  b {
    font-weight: normal; // :(
  }
}
```

You may have different taste. To be honest most of this should be controlled by your UI theme so maybe you just need to override the bold.

**Comment by vstastny** [comment]
Thanks a lot. I will definitely try.

**Comment by vstastny** [comment]
Works nicely. Thanks again.

**Comment by kritzcreek** [comment]
I think we can close this?

**Comment by nwolverson** [comment]
I suppose so, the blue tooltip is actually part of your atom user styles, and will appear differently if you choose a different user theme. The only obviously bad thing here is the use of bold.

Can look in future to do something more intelligent if it becomes easy
