### ISSUE TITLE
Always get Error for completion

### ISSUE THREAD

**Issue by jutaro** [nwolverson/atom-ide-purescript#79]
psc --version 0.8.5.0
psc-ide-server --version 0.8.5.0

Error: Error parsing Command. at Object.exports.error (/home/jutaro/.atom/packages/ide-purescript/lib/main.js:2263:12) at /home/jutaro/.atom/packages/ide-purescript/lib/main.js:5613:120 at /home/jutaro/.atom/packages/ide-purescript/lib/main.js:2155:23 at /home/jutaro/.atom/packages/ide-purescript/lib/main.js:2099:13 at Socket. (/home/jutaro/.atom/packages/ide-purescript/lib/main.js:4757:25) at emitNone (events.js:72:20) at Socket.emit (events.js:166:7) at endReadableNT (_stream_readable.js:905:12) at doNTCallback2 (node.js:465:9) at process._tickCallback (node.js:379:17)

**Comment by nwolverson** [comment]
I'll take a look at this tonight. In the meantime can you check the developer console, and find the version/path for psc-ide-server logged on startup - often this doesn't match what you expect.

**Comment by jutaro** [comment]
Seems like expected:
/home/jutaro/.cabal/bin/psc-ide-server: 0.8.5.0

Thanks for your quick answer

2016-06-06 12:47 GMT+02:00 Nicholas Wolverson notifications@github.com:

**Comment by nwolverson** [comment]
OK, in that case can you try running `psc-ide-server --debug` by hand in the project directory before opening the project in atom, see if something fishy is printed when the completion happens.

**Comment by nwolverson** [comment]
Did you manage to try this out? It still looks suspiciously like some kind of mismatched versions issue. I wonder if the logged version was correct but an existing server was running (do you see 'started server' popup at start or 'found an existing psc-ide-server')

**Comment by nwolverson** [comment]
Closing due to lack of follow-up & outdated versions. Please follow up if this still proves to be an issue.
