### ISSUE TITLE
PSCi console needs to support terminal colours

### ISSUE THREAD

**Issue by schrepfler** [nwolverson/atom-ide-purescript#80]
As per title.

**Comment by nwolverson** [comment]
Needs to? Is the display broken (showing colour codes as text or suchlike) or just not coloured?

I'm assuming this is 0.9 related

**Comment by schrepfler** [comment]
It's not coloured, this is correct im in ps 0.9.1 and new pulp.

**Comment by mrkgnao** [comment]
@nwolverson it _needs_ to. I'm on a fresh (yesterday, actually) Arch install and color codes show up as text in the PSCI console in Atom. 

Typing `main` into the input field and pressing Enter gives me an `Unknown value [33mmain[0m` error.

**Comment by nwolverson** [comment]
Oh thanks @mrkgnao, that's the opposite answer, I'll have to look into it.

Really what we want is a protocol to talk to psci rather than it giving its terminal output...

**Comment by nwolverson** [comment]
Colors should now work 047a4d39c61e6ee1a548b4596e7e5046ac414dc1 0.13.5

**Comment by schrepfler** [comment]
Works, cheers!

**Comment by mrkgnao** [comment]
Can confirm that it works too.
