### ISSUE TITLE
Couldn't find psc-ide-server on Windows

### ISSUE THREAD

**Issue by garyb** [nwolverson/atom-ide-purescript#83]
I've just updated to the latest version and now I'm getting this error popping up on Windows:

```
Couldn't find psc-ide-server, check PATH. Looked for: psc-ide-server in PATH:
```

I'm not sure what's happened really, it was working right until I restarted Atom after updating, and `psc-ide-server` is definitely on the PATH. I tried switching it to `psc-ide-server.exe` just in case, but that didn't help either.

If I enter the full path explicitly it works, but I'd prefer to avoid that, since I sync my config between OSX and Windows.

**Comment by nwolverson** [comment]
I think it should log the PATH it found in the console? It uses node-which, so should find either `psc-ide-server.cmd` or `psc-ide-server.exe` in the PATH and (use the first one)

**Comment by garyb** [comment]
Hmm, interesting. I don't see anything in the console, but it looks like it "should" be printing the path in the message I pasted above. I didn't truncate it, it is just printing `PATH:` as the end of the message.

**Comment by nwolverson** [comment]
Can you try evaluating `process.env.PATH` in the console? If that's not what you expect also I think there are plugins that try to fix atom's path somehow, might want to check if any of those are an issue

**Comment by garyb** [comment]
Hmm, weird. It seems to be this atom/atom#11302 even though I'm on Atom 1.8. I just renamed my environment variable to make it work, which doesn't really seem right, but hey, it works! Thanks.
