### ISSUE TITLE
red underline doesn't appear when only once char is problematic

### ISSUE THREAD

**Issue by rvion** [nwolverson/atom-ide-purescript#87]
Hello

here, I can see that I have an error on the line, but the `=` sign is not underlined.

![image](https://cloud.githubusercontent.com/assets/2150990/16730876/946c91fa-4775-11e6-903c-a0ab7625fed5.png)

I think it's easilly fixable, because when I place my cursor right before the `=` sign, atom show the tooltip as expected

![image](https://cloud.githubusercontent.com/assets/2150990/16730887/9a098276-4775-11e6-947b-6fa3df3117a9.png)

I think there should be a visible red underline below the `=`, as for regular errors (like 
![image](https://cloud.githubusercontent.com/assets/2150990/16730977/11e62dd0-4776-11e6-8f70-68192eade845.png)

)

**Comment by nwolverson** [comment]
I think this is missing position information on psc syntax errors (start/end is the same position)

**Comment by rvion** [comment]
@nwolverson How about considering same position for start and end as either
- a one character error ?
- next word is an error ?

since this is a syntax error, I don't know if purescript can give better indication about the "end"

**Comment by rvion** [comment]
here is an other example of missing red underline:

![image](https://cloud.githubusercontent.com/assets/2150990/16759805/015ae23c-4819-11e6-8626-8ba3672dcf0f.png)

**Comment by nwolverson** [comment]
@rvion could you check that hole one with psc if the position info is correct - probably it should be added to the collection at https://github.com/purescript/purescript/issues/1801 - unless it's at the end of your file, in which case that is a general compiler issue I think (see comment in same issue)

**Comment by rvion** [comment]
Can you assign this one to me so I don't forget to get back to it soon (can't check right now)

**Comment by nwolverson** [comment]
Apparently can't assign without making a collaborator. Will check or follow up

**Comment by nwolverson** [comment]
Hole error is simply that it is the end of the file, such error position always an issue. Underline is normal otherwise.
