### ISSUE TITLE
buggy warning tooltips when several newlines

### ISSUE THREAD

**Issue by rvion** [nwolverson/atom-ide-purescript#88]
where there is several newlines, warning tooltips are not displayed properly

![image](https://cloud.githubusercontent.com/assets/2150990/16731065/7ca31c0a-4776-11e6-84e5-2a9c19cc200f.png)

**Comment by nwolverson** [comment]
I'm sure this is an issue with the atom "linter" package (or its UI package, which has now been split out) but I couldn't track down a related issue yet (if you see one...)

**Comment by nwolverson** [comment]
I think this is now resolved with new linter. Or maybe replaced by different problems.
