### ISSUE TITLE
`add type signature` functionality is not directly discoverable

### ISSUE THREAD

**Issue by rvion** [nwolverson/atom-ide-purescript#89]
- How about adding a specific command ?
- How about a small line in the readme regarding the possibility to add type signature via <alt+enter> followed by an other <enter> ?

**Comment by nwolverson** [comment]
Not sure what you mean about "add type signature". If this is the quick-fix from the compiler suggestion, this is generic behaviour to apply any compiler quick fix - see here https://github.com/nwolverson/atom-ide-purescript#error-suggestions

There can be no specific command but we could list the known compiler suggestions & be a bit more explicit there about the UI

**Comment by rvion** [comment]
> Not sure what you mean about "add type signature". If this is the quick-fix from the compiler suggestion, this is generic behaviour to apply any compiler quick fix - see here https://github.com/nwolverson/atom-ide-purescript#error-suggestions

indeed, I was speaking about that.
It just took me some time to discover I could add type signature with it.
I previsouly quickly searched on the readme for type-signature, but didn't found anything, so I thought it was not yet present. the feature is great, just not "easilly" discoverable :)

> There can be no specific command but we could list the known compiler suggestions & be a bit more explicit there about the UI

yes, that's just what I was thinking about

---

edit: arg, I just noticed that github markdown ate my initial text -__-'
I wanted to write in my initial post:

> How about a small line in the readme regarding the possibility to add type signature via  `alt-enter` followed by an other `enter` ?

**Comment by nwolverson** [comment]
Would be more discoverable if there was some kind of nice UI, like the usual lightbulb, but such I UI I think is outside of the scope of this package - if it's built in a reusable way somewhere else, I'd use it.
