### ISSUE TITLE
type signature addition via "quick-fix from the compiler" feature is buggy

### ISSUE THREAD

**Issue by rvion** [nwolverson/atom-ide-purescript#94]
type signature addition via "quick-fix from the compiler" feature is buggy
- 1. 🔶 sometimes it add one blank line above the function
- 2. 🔶 sometimes it can add many lines
- 3. 🔴 sometimes it write the type signature in the middle of an other signaure, thus breaking the code

here are examples
(those are made up examples, but I experimented the bug on real code)
### one extra blank line example:

| before | after |
| --- | --- |
| ![image](https://cloud.githubusercontent.com/assets/2150990/16732920/a846ae2c-477f-11e6-92a9-c7bc7bce3819.png) | ![image](https://cloud.githubusercontent.com/assets/2150990/16732929/b00a4286-477f-11e6-8ea0-ee036c5f321e.png) |
### many extra blank lines example:

| before | after |
| --- | --- |
| ![image](https://cloud.githubusercontent.com/assets/2150990/16733016/05d3f1bc-4780-11e6-9f01-2c2a5fa31689.png) | ![image](https://cloud.githubusercontent.com/assets/2150990/16733033/234cb850-4780-11e6-9944-5fb652fabfe1.png) |
### breaking code example

| before | after |
| --- | --- |
| ![image](https://cloud.githubusercontent.com/assets/2150990/16733153/9dab20a0-4780-11e6-86ea-8baab72c76ca.png) | ![image](https://cloud.githubusercontent.com/assets/2150990/16733158/a8c32b68-4780-11e6-8a17-acc42046f86b.png) |

**Comment by nwolverson** [comment]
Definitely something off about the quick-fix stuff since relatively recently, I see it on imports too.

For the third case did you maybe do something else since last saving/building? I feel like the document position is not being updated on editing/applying other suggestions any more.

**Comment by rvion** [comment]
@nwolverson I didn't do anything special

here is a full file you can use to reproduce the bug 🐛 :

``` purescript
module Main where

import Prelude
import Control.Monad.Eff (Eff)
import Control.Monad.Eff.Console (CONSOLE, log)
import Control.Monad.Eff.Random (RANDOM, randomInt)
-- import Data.Boolean (otherwise)

foo22 = do
  log "Hello sailor!"
  xx <- randomInt 2 10
  log ("log" <> show xx)
  foo22


-- comment 2









main :: forall t15 t2.
  Eff
    ( console :: CONSOLE
    , random :: RANDOM
    | t15
    )
    t2
main = foo22

tesdezt = foo22 -- <-------- CURSOR HERE, within `tesdezt` word












-- ok

```

my crusor is on 35:4

![image](https://cloud.githubusercontent.com/assets/2150990/16733581/5cca0086-4782-11e6-9387-05e166a2f1db.png)

**Comment by rvion** [comment]
@nwolverson 

it seems that the quickfix function also add newlines when switching imports to `explicit` form

| before | after |
| --- | --- |
| ![image](https://cloud.githubusercontent.com/assets/2150990/16742519/45dd8f2a-47a8-11e6-9425-8c32d84c570c.png) | ![image](https://cloud.githubusercontent.com/assets/2150990/16742556/6c961538-47a8-11e6-9f01-75924eb63acf.png) |

**Comment by nwolverson** [comment]
@rvion yes, it does, both make explicit and remove unused import used to work perfectly until I think I made some changes in the compiler... This is high on the todo list, it's annoying no doubt.
