### ISSUE TITLE
go-to declaration

### ISSUE THREAD

**Issue by rvion** [nwolverson/atom-ide-purescript#96]
not sure if this kind of issue is useful, but in case it helps, here is it: https://github.com/epost/psc-ide-emacs/pull/66

**Comment by nwolverson** [comment]
For sure, will be good. @kRITZCREEK this landed in 0.9.2 ?

**Comment by kritzcreek** [comment]
Yes. You need to pass source globs to `psc-ide-server`though, and I'm not sure where to get these yet for the editors.

**Comment by nwolverson** [comment]
Implemented 3da674ed92ae707150bfe0fa1082c430361002b3 (globs are specified in config but the usual defaults)
