### ISSUE TITLE
[sugestion] type tooltip henhancement: colors + clickable links + optionally stripped prefix + ...? 

### ISSUE THREAD

**Issue by rvion** [nwolverson/atom-ide-purescript#97]
in a PR I did for https://github.com/lukexi/stack-ide-sublime/pull/36, I tried to style type tooltips a little bit and managed to get 
- basic colors
- clickable links
- optionally stripped prefix (instead of `Int -> Stuff.Qualified.TooLong.foo`, only `Int -> _foo` was displayed - it was pragmatic is situations where functions were rely on inference a lot and where I hadn't all types in scope (i.e: lens, etc.))

![image](https://cloud.githubusercontent.com/assets/2150990/11168603/f8d7329e-8b96-11e5-94a8-075e1d7e5e72.png)

clicking on `middleware` would open documentation
![image](https://cloud.githubusercontent.com/assets/2150990/11168614/92f97102-8b97-11e5-84c2-402ecaa3aef6.png) 
- I wonder if something similar is possible in Atom
- I also wonder what else could make it in a tooltip 2.0 :)

**Comment by nwolverson** [comment]
I've mentioned before considering the ide-haskell atom package's tooltip style, there were some gripes with it but I think that was positioning  (for me it's performance).

I think using standard syntax highlighting in the tooltips would be an idea. Prefixes are an issue for completion also, possibly should reflect current scope, not sure. Clickable tooltips, not so sure...

**Comment by rvion** [comment]
some feedback:

the more the code grow, the more I have things like that:

![image](https://cloud.githubusercontent.com/assets/2150990/16846231/dea1f1c0-49eb-11e6-80e9-02f848d305fa.png)

(half of a large type)

**Comment by kritzcreek** [comment]
The compiler or psc-ide are the culprits here. Because type synonyms get fully expanded before being written to the output folder, psc-ide can only pick those types up. Also currently psc-ide merely gives back a string, so for some sort of folding of records we'd need to change the format with which we send around types.

**Comment by kritzcreek** [comment]
A note related to the aforementioned long type tooltip. `psc-ide` uses the parsed source files to look up non-expanded types in recent versions and so this situation shouldn't arrive unless you annotated your function with a type that long ;)

**Comment by nwolverson** [comment]
Don't think there's anything concrete left here.
