### ISSUE TITLE
[feature request] automatically suggest fix for missing imports

### ISSUE THREAD

**Issue by rvion** [nwolverson/atom-ide-purescript#98]
when imports are missing,

![image](https://cloud.githubusercontent.com/assets/2150990/16801705/928490e4-48fc-11e6-95c5-f8bc1f8202b2.png)

it would be great if quickfix (`<alt>-<enter>` ) could offer to add a few imports.

![image](https://cloud.githubusercontent.com/assets/2150990/16801692/8412e81c-48fc-11e6-8a63-77682d6f10e7.png)

I don't really know if it is related to the current pursuit problems, but as of right now I have to use google everytime I'm looking for symbols. it's quite painfull

**Comment by kritzcreek** [comment]
with that error I think you can put your cursor on top of `Monad` in your source file and execute an add import command through the command palette.

**Comment by nwolverson** [comment]
I think this is sort of there for some kinds of identifier - I think for values maybe, @kRITZCREEK added a "fix typo" which will find similar identifiers & add the import.

(Tip - You can actually position your cursor after the word and hit ctrl+space to trigger completion, if there is one option that will automatically (and silently...) add the import )

**Comment by rvion** [comment]
both 

> put your cursor on top of Monad in your source file and execute an add import command through the command palette

and 

> You can actually position your cursor after the word and hit ctrl+space to trigger completion, if there is one option that will automatically (and silently...) add the import 

worked, thanks !

**Comment by nwolverson** [comment]
Was going to say the fix typo could be extended to be suggested on this error but the problem may be the source position is not tight enough, and that will require some further compiler work. Possible hacks aside.

**Comment by rvion** [comment]
Just for the record: 

both when
- Hitting autocompletion (`<ctrl>-<space`) and completeing with `monad`
- Using the `Add Module Import`

I get this:

![image](https://cloud.githubusercontent.com/assets/2150990/16802009/682a08cc-48fe-11e6-9b63-bbea6ff8811c.png)

**Comment by kritzcreek** [comment]
yeah `bind` is a bit of a bummer. It's automatically to be assumed in scope when you are using do notation. I suggest to import the Prelude unqualified and open while explicitly importing your other modules. You can also add `bind` to the Prelude's import list.

EDIT: Monad is also in the Prelude, so you shouldn't need to import that either after importing the prelude "open"

**Comment by rvion** [comment]
The fun thing is that I can't use autocompletion here to bring `bind` in scope nor select it and hit `import command`

(still can use `add Explicit Import` function, though)

**Comment by rvion** [comment]
> Was going to say the fix typo could be extended to be suggested on this error but the problem may be the source position is not tight enough, and that will require some further compiler work. Possible hacks aside.

Indeed, I think it would be great if quickfix `<alt><enter>` could offer to `Add explicit import`, directly with the missing name pre-filled

**Comment by rvion** [comment]
After a few days of usage, I think that 
- the `<tab>` shortcut to trigger autocompletion when you want to import something is really practical
-  the `add module import` is more than enough for other cases.

so I don't think anymore that doing more worth the extra complexity.
I'll close this unless you think it was a nice enhancement proposal

**Comment by nwolverson** [comment]
Reopening, think there is definitely something worth doing here, without too much effort.

**Comment by rvion** [comment]
ok :)

**Comment by nwolverson** [comment]
OK, seems there is already quick-fix triggered by these error codes (for simple unknown identifiers, not fancy things like bind), but needed updating for the current error code.
